// =============================================================================
// Tatka Bazar — Rich Authentic Bangladeshi Catalogue Dataset
// =============================================================================

import { Product, Category, VendorShop, Branch, Review } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-fish-meat",
    slug: "fish-and-meat",
    nameBn: "মাছ ও মাংস",
    nameEn: "Fish & Meat",
    descriptionBn: "নদী ও সমুদ্রের তাজা মাছ এবং স্বাস্থ্যসম্মত দেশি মাংস",
    descriptionEn: "Fresh river & sea fish, premium organic chicken & mutton",
    icon: "🐟",
    image: "https://images.unsplash.com/photo-1544943910-4c1dc44a0b27?w=600&auto=format&fit=crop&q=80",
    itemCount: 42,
    subcategories: [
      { slug: "fresh-river-fish", nameBn: "নদীর তাজা মাছ", nameEn: "River Fish" },
      { slug: "sea-fish", nameBn: "সামুদ্রিক মাছ", nameEn: "Sea Fish" },
      { slug: "desi-chicken", nameBn: "দেশি মুরগি", nameEn: "Country Chicken" },
      { slug: "mutton-beef", nameBn: "খাসি ও গরুর মাংস", nameEn: "Beef & Mutton" },
    ],
  },
  {
    id: "cat-veg",
    slug: "vegetables",
    nameBn: "শাকসবজি",
    nameEn: "Fresh Vegetables",
    descriptionBn: "সরাসরি মাঠ থেকে ভোরে তোলা ১০০% সতেজ ও কীটনাশকমুক্ত শাকসবজি",
    descriptionEn: "Farm-fresh pesticide-free morning harvest greens & vegetables",
    icon: "🥬",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    itemCount: 58,
    subcategories: [
      { slug: "leafy-greens", nameBn: "তাজা শাক", nameEn: "Leafy Greens" },
      { slug: "daily-veg", nameBn: "নিত্যপ্রয়োজনীয় সবজি", nameEn: "Daily Veggies" },
      { slug: "salad-items", nameBn: "সালাদ আইটেম", nameEn: "Salad Items" },
    ],
  },
  {
    id: "cat-fruits",
    slug: "fruits",
    nameBn: "ফলমূল",
    nameEn: "Fresh Fruits",
    descriptionBn: "ফরমালিনমুক্ত দেশি ও বিদেশি রসালো পুষ্টিকর ফল",
    descriptionEn: "100% formalin-free seasonal and imported premium fruits",
    icon: "🥭",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80",
    itemCount: 35,
    subcategories: [
      { slug: "seasonal-fruits", nameBn: "মৌসুমি ফল", nameEn: "Seasonal Fruits" },
      { slug: "imported-fruits", nameBn: "আমদানি ফল", nameEn: "Imported Fruits" },
      { slug: "citrus-berries", nameBn: "লেবু ও সাইট্রাস", nameEn: "Citrus & Berries" },
    ],
  },
  {
    id: "cat-rice-grains",
    slug: "rice-and-staples",
    nameBn: "চাল, ডাল ও নিত্যপণ্য",
    nameEn: "Rice, Lentils & Staples",
    descriptionBn: "দিনাজপুরের সেরা চাল, দেশি ডাল, আটা-ময়দা ও নিত্যপ্রয়োজনীয় মুদি",
    descriptionEn: "Aromatic Dinajpur rice, organic lentils, flour & pantry essentials",
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    itemCount: 64,
    subcategories: [
      { slug: "premium-rice", nameBn: "সুগন্ধি ও প্রিমিয়াম চাল", nameEn: "Aromatic & Fine Rice" },
      { slug: "lentils-dal", nameBn: "দেশি ডাল", nameEn: "Organic Lentils" },
      { slug: "flour-atta", nameBn: "আটা ও ময়দা", nameEn: "Atta & Flour" },
    ],
  },
  {
    id: "cat-oil-ghee",
    slug: "oil-and-ghee",
    nameBn: "তেল, ঘি ও মসলা",
    nameEn: "Oil, Ghee & Spices",
    descriptionBn: "ঘানিতে ভাঙা খাঁটি সরিষার তেল, গাওয়া ঘি ও বাছাইকৃত গুঁড়া মসলা",
    descriptionEn: "Cold-pressed mustard oil, pure cow ghee and authentic spices",
    icon: "🫒",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
    itemCount: 48,
    subcategories: [
      { slug: "mustard-oil", nameBn: "সরিষার তেল", nameEn: "Mustard Oil" },
      { slug: "pure-ghee", nameBn: "গাওয়া ঘি", nameEn: "Desi Ghee" },
      { slug: "ground-spices", nameBn: "গুঁড়া মসলা", nameEn: "Ground Spices" },
    ],
  },
  {
    id: "cat-dairy-eggs",
    slug: "dairy-and-eggs",
    nameBn: "দুধ, দই ও ডিম",
    nameEn: "Dairy, Curd & Eggs",
    descriptionBn: "খাঁটি তরল দুধ, বগুড়ার স্পেশাল দই ও লাল লেয়ার/দেশি ডিম",
    descriptionEn: "Farm-fresh milk, Bogura sweet curd, organic brown eggs",
    icon: "🥛",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    itemCount: 29,
  },
];

export const VENDORS: VendorShop[] = [
  {
    id: "vendor-green-grocer",
    slug: "green-grocer-bd",
    nameBn: "গ্রিন গ্রোসার বিডি",
    nameEn: "Green Grocer BD",
    taglineBn: "উন্নত জৈব ও পুষ্টিকর সবজির নির্ভরযোগ্য ঠিকানা",
    taglineEn: "Your trusted farm-to-table organic produce partner",
    logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 184,
    locationBn: "সাভার, ঢাকা",
    locationEn: "Savar, Dhaka",
    joinedYear: 2023,
    totalProducts: 48,
    verified: true,
    badgeBn: "🏆 শীর্ষ রেটেড ভেন্ডর",
    badgeEn: "🏆 Top Rated Seller",
  },
  {
    id: "vendor-padma-fish",
    slug: "padma-fish-house",
    nameBn: "পদ্মা রিভার ফিশ সাপ্লাই",
    nameEn: "Padma River Fish Supply",
    taglineBn: "চাঁদপুর ও গোয়ালন্দ ঘাট থেকে প্রতিদিনের তাজা নদী মাছ",
    taglineEn: "Daily fresh catch from Chandpur & Padma riverbanks",
    logo: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 312,
    locationBn: "চাঁদপুর ঘাট, চাঁদপুর",
    locationEn: "Chandpur Ghat, Chandpur",
    joinedYear: 2022,
    totalProducts: 32,
    verified: true,
    badgeBn: "🐟 ফ্রেশ ফিশ সার্টিফাইড",
    badgeEn: "🐟 Fresh Fish Certified",
  },
  {
    id: "vendor-bogra-dahi",
    slug: "bogra-shahi-dairy",
    nameBn: "বগুড়া শাহী ডেইরি ও মিষ্টি",
    nameEn: "Bogura Shahi Dairy & Sweets",
    taglineBn: "ঐতিহ্যবাহী বগুড়ার আসল ক্ষীরসা দই ও খাঁটি গাওয়া ঘি",
    taglineEn: "Authentic traditional Bogura curd and artisanal cow ghee",
    logo: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=1200&auto=format&fit=crop&q=80",
    rating: 5.0,
    reviewsCount: 96,
    locationBn: "বগুড়া সদর, বগুড়া",
    locationEn: "Bogura Sadar, Bogura",
    joinedYear: 2024,
    totalProducts: 18,
    verified: true,
    badgeBn: "⭐ ঐতিহ্যবাহী স্বাদ",
    badgeEn: "⭐ Authentic Heritage",
  },
];

export const PRODUCTS: Product[] = [
  // 1. Padma Ilish
  {
    id: "prod-ilish-padma",
    slug: "padma-fresh-ilish-fish",
    nameBn: "পদ্মার তাজা রূপালি ইলিশ (১ কেজি+ সাইজ)",
    nameEn: "Fresh Padma River Hilsa Fish (1kg+ size)",
    descriptionBn: "চাঁদপুরের মোহনা থেকে আহরিত পদ্মা নদীর তাজা চকচকে রূপালি ইলিশ মাছ। চমৎকার সুবাস ও ডিমযুক্ত রসালো স্বাদের নিশ্চয়তা। আমরা প্রতিদিন ভোরে মাছ সংগ্রহ করে বরফ ছাড়া নিয়ন্ত্রিত তাপমাত্রায় সরাসরি আপনার কাছে পাঠাই।",
    descriptionEn: "Premium whole silver Hilsa harvested from the Chandpur confluence of Padma river. Unmatched authentic aroma, rich oily texture and peak freshness delivered in pristine condition.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "মাছ ও মাংস",
    categoryNameEn: "Fish & Meat",
    basePrice: 1450,
    comparePrice: 1650,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.8, unit: "kg", labelBn: "৮০০ গ্রাম (মাঝারি)", labelEn: "800g (Medium)", multiplier: 0.8 },
      { value: 1.0, unit: "kg", labelBn: "১ কেজি (স্ট্যান্ডার্ড)", labelEn: "1 kg (Standard)", multiplier: 1.0, popular: true },
      { value: 1.2, unit: "kg", labelBn: "১.২ কেজি (বড় সাইজ)", labelEn: "1.2 kg (Large)", multiplier: 1.25 },
      { value: 1.5, unit: "kg", labelBn: "১.৫ কেজি (কিং সাইজ)", labelEn: "1.5 kg (King Size)", multiplier: 1.6 },
    ],
    tieredPricing: [
      { minQty: 2, pricePerUnit: 1400, discountPercent: 4, labelBn: "২ কেজি+ নিলে ৳১৪০০/কেজি", labelEn: "2kg+ at ৳1400/kg" },
      { minQty: 5, pricePerUnit: 1320, discountPercent: 9, labelBn: "৫ কেজি+ নিলে ৳১৩২০/কেজি", labelEn: "5kg+ at ৳1320/kg" },
    ],
    stock: 28,
    images: [
      "https://images.unsplash.com/photo-1544943910-4c1dc44a0b27?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 12,
    originBn: "চাঁদপুর মোহনা, পদ্মা নদী",
    originEn: "Chandpur River Estuary, Padma River",
    freshnessGuaranteeBn: "ভোরে আহরিত ও ১ দিন লাইফটাইম",
    freshnessGuaranteeEn: "Harvested at dawn, same-day delivery",
    nutritionInfo: {
      calories: "285 kcal",
      protein: "22.5g",
      carbs: "0.2g",
      fat: "19.4g (ওমেগা ৩ সমৃদ্ধ)",
    },
    storageTipsBn: "কাটার পর সামান্য লবণ মেখে ডিপ ফ্রিজে রাখলে স্বাদ ও সুবাস অক্ষুণ্ণ থাকে।",
    storageTipsEn: "Rub with light salt and freeze immediately to preserve maximum aroma.",
    rating: 4.9,
    reviewsCount: 88,
    vendorId: "vendor-padma-fish",
    vendorNameBn: "পদ্মা রিভার ফিশ সাপ্লাই",
    vendorNameEn: "Padma River Fish Supply",
    vendorSlug: "padma-fish-house",
    isOfficialTatka: false,
    sku: "FISH-ILISH-001",
  },

  // 2. Organic Tomato
  {
    id: "prod-tomato-organic",
    slug: "organic-red-tomatoes",
    nameBn: "পাকা লাল দেশি টমেটো (১০০% অর্গানিক)",
    nameEn: "Organic Red Farm Tomatoes (Pesticide Free)",
    descriptionBn: "মাঠ থেকে তোলা সতেজ টসটসে পাকা টমেটো। কোনো রকম কৃত্রিম পাকানোর কেমিক্যাল বা কার্বাইড ছাড়া সম্পূর্ণ প্রাকৃতিকভাবে পাকা। সালাদ ও রান্নার জন্য আদর্শ।",
    descriptionEn: "Plump, naturally vine-ripened red tomatoes picked daily from organic farms in Savar. Juicy and nutrient-dense with zero chemical ripening agents.",
    categorySlug: "vegetables",
    categoryNameBn: "শাকসবজি",
    categoryNameEn: "Fresh Vegetables",
    basePrice: 65,
    comparePrice: 80,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "২৫০ গ্রাম", labelEn: "250g", multiplier: 0.25 },
      { value: 0.5, unit: "kg", labelBn: "৫০০ গ্রাম", labelEn: "500g", multiplier: 0.5 },
      { value: 1.0, unit: "kg", labelBn: "১ কেজি", labelEn: "1 kg", multiplier: 1.0, popular: true },
      { value: 2.0, unit: "kg", labelBn: "২ কেজি", labelEn: "2 kg", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelBn: "৫ কেজি (ফ্যামিলি প্যাক)", labelEn: "5 kg (Family Pack)", multiplier: 4.8 },
    ],
    tieredPricing: [
      { minQty: 3, pricePerUnit: 60, discountPercent: 8, labelBn: "৩ কেজি+ নিলে ৳৬০/কেজি", labelEn: "3kg+ at ৳60/kg" },
      { minQty: 10, pricePerUnit: 52, discountPercent: 20, labelBn: "১০ কেজি+ নিলে ৳৫২/কেজি", labelEn: "10kg+ at ৳52/kg" },
    ],
    stock: 150,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1546470427-e26264be0b11?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 18,
    originBn: "সাভার ও নরসিংদী খামার",
    originEn: "Savar & Narsingdi Organic Farms",
    freshnessGuaranteeBn: "ভোরের তাজা ফসল",
    freshnessGuaranteeEn: "Fresh morning harvest",
    nutritionInfo: {
      calories: "18 kcal",
      protein: "0.9g",
      carbs: "3.9g",
      fat: "0.2g (লাইকোপিন সমৃদ্ধ)",
    },
    storageTipsBn: "সাধারণ তাপমাত্রায় বায়ু চলাচল হয় এমন স্থানে সংরক্ষণ করুন।",
    storageTipsEn: "Keep at cool room temperature for the best natural sweetness.",
    rating: 4.8,
    reviewsCount: 142,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "গ্রিন গ্রোসার বিডি",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "VEG-TOMATO-002",
  },

  // 3. Kataribhog Rice (Official Tatka Stock)
  {
    id: "prod-rice-kataribhog",
    slug: "dinajpur-kataribhog-aromatic-rice",
    nameBn: "দিনাজপুরের স্পেশাল সুগন্ধি কাটারিভোগ চাল",
    nameEn: "Dinajpur Premium Kataribhog Aromatic Rice",
    descriptionBn: "দিনাজপুরের বিখ্যাত চিকন ও সুগন্ধি কাটারিভোগ আতপ চাল। পোলাও, বিরিয়ানি ও প্রতিদিনের মজাদার ভাতের জন্য সর্বোৎকৃষ্ট। চাল পরিষ্কার, সম্পূর্ণ পলিশমুক্ত ও শতভাগ খাঁটি।",
    descriptionEn: "Authentic, naturally aged aromatic Kataribhog grain from Dinajpur. Extremely fluffy, pristine and free from industrial wax or artificial polish.",
    categorySlug: "rice-and-staples",
    categoryNameBn: "চাল, ডাল ও নিত্যপণ্য",
    categoryNameEn: "Rice, Lentils & Staples",
    basePrice: 110,
    comparePrice: 125,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "১ কেজি", labelEn: "1 kg", multiplier: 1.0 },
      { value: 2.0, unit: "kg", labelBn: "২ কেজি", labelEn: "2 kg", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelBn: "৫ কেজি বস্তা", labelEn: "5 kg Bag", multiplier: 4.9, popular: true },
      { value: 25.0, unit: "kg", labelBn: "২৫ কেজি মন ব্যাগ (পাইকারি)", labelEn: "25 kg Sack (Wholesale)", multiplier: 23.5 },
    ],
    tieredPricing: [
      { minQty: 5, pricePerUnit: 105, discountPercent: 5, labelBn: "৫ কেজি+ নিলে ৳১০৫/কেজি", labelEn: "5kg+ at ৳105/kg" },
      { minQty: 25, pricePerUnit: 98, discountPercent: 11, labelBn: "২৫ কেজি+ নিলে ৳৯৮/কেজি", labelEn: "25kg+ at ৳98/kg" },
    ],
    stock: 500,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    originBn: "বিরল, দিনাজপুর",
    originEn: "Birol, Dinajpur",
    freshnessGuaranteeBn: "নতুন মৌসুমের সেরা চাল",
    freshnessGuaranteeEn: "New season harvest, aged naturally",
    nutritionInfo: {
      calories: "360 kcal",
      protein: "7.1g",
      carbs: "79.0g",
      fat: "0.6g",
    },
    rating: 4.9,
    reviewsCount: 64,
    vendorNameBn: "তাতকা বাজার নিজস্ব স্টক",
    vendorNameEn: "Tatka Bazar Official",
    vendorSlug: "tatka-bazar-official",
    isOfficialTatka: true,
    sku: "GRAIN-KATARI-003",
  },

  // 4. Pure Gawa Ghee
  {
    id: "prod-bogra-ghee",
    slug: "pure-gawa-ghee-bogura",
    nameBn: "খাঁটি দেশি গাওয়া ঘি (বগুড়ার ঐতিহ্যবাহী)",
    nameEn: "Pure Desi Cow Ghee (Traditional Bogura)",
    descriptionBn: "গাভীর খাঁটি দুধের মাখন জ্বাল দিয়ে তৈরি দানাদার সোনালী রঙের সুগন্ধি গাওয়া ঘি। কোনো কেমিক্যাল, ফ্লেভার বা ডালডা মুক্ত শতভাগ গ্যারান্টি।",
    descriptionEn: "Artisanal golden cow ghee churned from fresh farm milk butter in Bogura. Natural grainy texture, heavenly aroma, and 100% pure guarantee.",
    categorySlug: "oil-and-ghee",
    categoryNameBn: "তেল, ঘি ও মসলা",
    categoryNameEn: "Oil, Ghee & Spices",
    basePrice: 1350,
    comparePrice: 1500,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "২৫০ গ্রাম কাচের জার", labelEn: "250g Glass Jar", multiplier: 0.28 },
      { value: 0.5, unit: "kg", labelBn: "৫০০ গ্রাম কাচের জার", labelEn: "500g Glass Jar", multiplier: 0.52, popular: true },
      { value: 1.0, unit: "kg", labelBn: "১ কেজি প্রিমিয়াম পট", labelEn: "1 kg Premium Pot", multiplier: 1.0 },
    ],
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    originBn: "শেরপুর, বগুড়া",
    originEn: "Sherpur, Bogura",
    freshnessGuaranteeBn: "তাজা জ্বাল দেওয়া",
    freshnessGuaranteeEn: "Freshly churned batch",
    nutritionInfo: {
      calories: "884 kcal",
      protein: "0.2g",
      carbs: "0g",
      fat: "99.5g (ভিটামিন এ, ডি, ই সমৃদ্ধ)",
    },
    rating: 5.0,
    reviewsCount: 96,
    vendorId: "vendor-bogra-dahi",
    vendorNameBn: "বগুড়া শাহী ডেইরি ও মিষ্টি",
    vendorNameEn: "Bogura Shahi Dairy & Sweets",
    vendorSlug: "bogra-shahi-dairy",
    isOfficialTatka: false,
    sku: "DAIRY-GHEE-004",
  },

  // 5. Fresh Rui Fish
  {
    id: "prod-rui-fish",
    slug: "fresh-rui-fish-whole-cut",
    nameBn: "তাজা দেশি রুই মাছ (আস্ত বা পিস কাটিং)",
    nameEn: "Fresh Local Rui Fish (Cleaned & Cut)",
    descriptionBn: "মেঘনা ও হাওর অঞ্চলের মিষ্টি পানির জীবন্ত তাজা রুই মাছ। অর্ডার পাওয়ার পর আপনার পছন্দমতো আঁশ ছাড়িয়ে ও টুকরো করে যত্নসহকারে প্যাক করে ডেলিভারি দেওয়া হয়।",
    descriptionEn: "Live fresh sweet-water Rui fish sourced from Meghna river basin. Customized descaling and curry-cut preparation before immediate iced dispatch.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "মাছ ও মাংস",
    categoryNameEn: "Fish & Meat",
    basePrice: 420,
    comparePrice: 480,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "১ কেজি (মাঝারি পিস)", labelEn: "1 kg (Curry Cut)", multiplier: 1.0 },
      { value: 1.5, unit: "kg", labelBn: "১.৫ কেজি (বড় সাইজ)", labelEn: "1.5 kg (Whole Fish)", multiplier: 1.5, popular: true },
      { value: 2.5, unit: "kg", labelBn: "২.৫ কেজি (জায়ান্ট রুই)", labelEn: "2.5 kg (Giant Rui)", multiplier: 2.45 },
    ],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80",
    ],
    isDailyBazar: true,
    flashDiscount: 14,
    originBn: "মেঘনা নদী ও কিশোরগঞ্জ হাওর",
    originEn: "Meghna River & Kishoreganj Haor",
    freshnessGuaranteeBn: "আজকের লাইভ মাছ",
    freshnessGuaranteeEn: "Daily live catch",
    rating: 4.7,
    reviewsCount: 52,
    vendorId: "vendor-padma-fish",
    vendorNameBn: "পদ্মা রিভার ফিশ সাপ্লাই",
    vendorNameEn: "Padma River Fish Supply",
    vendorSlug: "padma-fish-house",
    isOfficialTatka: false,
    sku: "FISH-RUI-005",
  },

  // 6. Fresh Lal Shak (Red Spinach)
  {
    id: "prod-lal-shak",
    slug: "fresh-lal-shak-organic",
    nameBn: "তাজা কচি দেশি লাল শাক (১০০% অর্গানিক)",
    nameEn: "Fresh Desi Red Spinach (Lal Shak)",
    descriptionBn: "ভোরে মাঠ থেকে তোলা কচি রক্তিম লাল শাক। মাটির গন্ধ ও ভিটামিন-এ ও আয়রনে ভরপুর। রান্না করলে সুন্দর লাল রঙ ও সুস্বাদু স্বাদের নিশ্চয়তা।",
    descriptionEn: "Tender, iron-rich crimson leafy spinach harvested freshly at sunrise. Rich in vitamins and zero pesticide residues.",
    categorySlug: "vegetables",
    categoryNameBn: "শাকসবজি",
    categoryNameEn: "Fresh Vegetables",
    basePrice: 35,
    comparePrice: 45,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "২৫০ গ্রাম (১ আঁটি)", labelEn: "250g (1 Bundle)", multiplier: 0.25 },
      { value: 0.5, unit: "kg", labelBn: "৫০০ গ্রাম (২ আঁটি)", labelEn: "500g (2 Bundles)", multiplier: 0.5, popular: true },
      { value: 1.0, unit: "kg", labelBn: "১ কেজি (ফ্যামিলি প্যাক)", labelEn: "1 kg (Family Pack)", multiplier: 0.95 },
    ],
    stock: 90,
    images: [
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isDailyBazar: true,
    flashDiscount: 20,
    originBn: "কেরানীগঞ্জ ও মুন্সিগঞ্জ",
    originEn: "Keraniganj & Munshiganj Organic Farms",
    freshnessGuaranteeBn: "ভোরের তোলা কচি শাক",
    freshnessGuaranteeEn: "Tender morning harvest",
    rating: 4.9,
    reviewsCount: 77,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "গ্রিন গ্রোসার বিডি",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "VEG-LALSHAK-006",
  },
];

export const BRANCHES: Branch[] = [
  {
    id: "branch-dhanmondi",
    nameBn: "ধানমন্ডি এক্সপ্রেস হাব",
    nameEn: "Dhanmondi Express Hub",
    areaBn: "ধানমন্ডি, ঢাকা",
    areaEn: "Dhanmondi, Dhaka",
    addressBn: "বাড়ি ২৭, রোড ৮/এ, ধানমন্ডি আ/এ, ঢাকা ১২০৯",
    addressEn: "House 27, Road 8/A, Dhanmondi R/A, Dhaka 1209",
    phone: "০১৭০১-১১১০০০",
    deliveryTimeBn: "৩০-৪৫ মিনিট",
    deliveryTimeEn: "30-45 mins",
    isOpen: true,
  },
  {
    id: "branch-gulshan",
    nameBn: "গুলশান ২ ফ্ল্যাগশিপ হাব",
    nameEn: "Gulshan 2 Flagship Hub",
    areaBn: "গুলশান ও বনানী, ঢাকা",
    areaEn: "Gulshan & Banani, Dhaka",
    addressBn: "প্লট ১২, রোড ১০৪, গুলশান ২, ঢাকা ১২১২",
    addressEn: "Plot 12, Road 104, Gulshan 2, Dhaka 1212",
    phone: "০১৭০১-২২২০০০",
    deliveryTimeBn: "৩০-৪৫ মিনিট",
    deliveryTimeEn: "30-45 mins",
    isOpen: true,
  },
  {
    id: "branch-uttara",
    nameBn: "উত্তরা হাব",
    nameEn: "Uttara Express Hub",
    areaBn: "উত্তরা (সেক্টর ১-১৮), ঢাকা",
    areaEn: "Uttara (Sectors 1-18), Dhaka",
    addressBn: "সেক্টর ৩, জসীমউদ্দীন অ্যাভিনিউ, উত্তরা, ঢাকা ১২৩০",
    addressEn: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka 1230",
    phone: "০১৭০১-৩৩৩০০০",
    deliveryTimeBn: "৪০-৫০ মিনিট",
    deliveryTimeEn: "40-50 mins",
    isOpen: true,
  },
  {
    id: "branch-mirpur",
    nameBn: "মিরপুর সেন্ট্রাল হাব",
    nameEn: "Mirpur Central Hub",
    areaBn: "মিরপুর ১-১৪ ও পল্লবী, ঢাকা",
    areaEn: "Mirpur 1-14 & Pallabi, Dhaka",
    addressBn: "মিরপুর ১০ গোলচত্বর সংলগ্ন, ঢাকা ১২১৬",
    addressEn: "Near Mirpur 10 Circle, Dhaka 1216",
    phone: "০১৭০১-৪৪৪০০০",
    deliveryTimeBn: "৩৫-৪৫ মিনিট",
    deliveryTimeEn: "35-45 mins",
    isOpen: true,
  },
  {
    id: "branch-ctg",
    nameBn: "চট্টগ্রাম জিইসি হাব",
    nameEn: "Chattogram GEC Hub",
    areaBn: "জিইসি, নাসিরাবাদ ও খুলশী, চট্টগ্রাম",
    areaEn: "GEC, Nasirabad & Khulshi, Chattogram",
    addressBn: "জিইসি মোড়, ও.আর. নিজাম রোড, চট্টগ্রাম ৪০০০",
    addressEn: "GEC Circle, O.R. Nizam Road, Chattogram 4000",
    phone: "০১৭০১-৫৫৫০০০",
    deliveryTimeBn: "৪৫-৬০ মিনিট",
    deliveryTimeEn: "45-60 mins",
    isOpen: true,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    userName: "তানভীর হাসান",
    userLocation: "ধানমন্ডি, ঢাকা",
    rating: 5,
    date: "২১ আগস্ট ২০২৬",
    commentBn: "পদ্মার ইলিশ মাছটা সত্যিই অসাধারণ তাজা ছিল! সকালে অর্ডার দিয়ে ৮:৩০ এর মধ্যেই পেয়ে গেছি। প্যাকিং খুব ভালো ছিল।",
    commentEn: "The Padma Hilsa was extraordinarily fresh! Ordered in the morning and received it before 8:30 AM. Superb packaging.",
    verifiedPurchase: true,
    likes: 24,
  },
  {
    id: "rev-2",
    userName: "ফারজানা আক্তার",
    userLocation: "গুলশান ২, ঢাকা",
    rating: 5,
    date: "২০ আগস্ট ২০২৬",
    commentBn: "শাকসবজি ১০০% অর্গানিক এবং একেবারেই ক্ষেত থেকে তোলার মতো সতেজ। ওজন ভিত্তিক কাস্টমাইজেশন সুবিধাটা দারুণ লেগেছে।",
    commentEn: "The vegetables are 100% organic and fresh like freshly harvested. Loved the weight-based customization feature!",
    verifiedPurchase: true,
    likes: 19,
  },
  {
    id: "rev-3",
    userName: "মাহমুদুর রহমান",
    userLocation: "উত্তরা, ঢাকা",
    rating: 5,
    date: "১৯ আগস্ট ২০২৬",
    commentBn: "বগুড়ার ঘি আর কাটারিভোগ চালের ঘ্রাণেই মন ভরে যায়। একাধিক বিক্রেতার পণ্য এক কার্টেই আলাদা প্যাকেটে পাওয়া গেছে। সেরা সেবা!",
    commentEn: "The aroma of Bogura ghee and Kataribhog rice is unmatched. Multi-vendor order splitting worked seamlessly. Top service!",
    verifiedPurchase: true,
    likes: 31,
  },
];
