// =============================================================================
// Tatka Bazar — Rich Authentic Bangladeshi Catalogue Dataset (English)
// =============================================================================

import { Product, Category, VendorShop, Branch, Review } from "@/types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-fish-meat",
    slug: "fish-and-meat",
    nameBn: "Fish & Meat",
    nameEn: "Fish & Meat",
    descriptionBn: "Fresh river & sea fish, premium organic chicken & mutton",
    descriptionEn: "Fresh river & sea fish, premium organic chicken & mutton",
    icon: "🐟",
    image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80",
    itemCount: 42,
    subcategories: [
      { slug: "fresh-river-fish", nameBn: "River Fish", nameEn: "River Fish" },
      { slug: "sea-fish", nameBn: "Sea Fish", nameEn: "Sea Fish" },
      { slug: "desi-chicken", nameBn: "Country Chicken", nameEn: "Country Chicken" },
      { slug: "mutton-beef", nameBn: "Beef & Mutton", nameEn: "Beef & Mutton" },
    ],
  },
  {
    id: "cat-veg",
    slug: "vegetables",
    nameBn: "Fresh Vegetables",
    nameEn: "Fresh Vegetables",
    descriptionBn: "Farm-fresh pesticide-free morning harvest greens & vegetables",
    descriptionEn: "Farm-fresh pesticide-free morning harvest greens & vegetables",
    icon: "🥬",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    itemCount: 58,
    subcategories: [
      { slug: "leafy-greens", nameBn: "Leafy Greens", nameEn: "Leafy Greens" },
      { slug: "daily-veg", nameBn: "Daily Veggies", nameEn: "Daily Veggies" },
      { slug: "salad-items", nameBn: "Salad Items", nameEn: "Salad Items" },
    ],
  },
  {
    id: "cat-fruits",
    slug: "fruits",
    nameBn: "Fresh Fruits",
    nameEn: "Fresh Fruits",
    descriptionBn: "100% formalin-free seasonal and imported premium fruits",
    descriptionEn: "100% formalin-free seasonal and imported premium fruits",
    icon: "🥭",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80",
    itemCount: 35,
    subcategories: [
      { slug: "seasonal-fruits", nameBn: "Seasonal Fruits", nameEn: "Seasonal Fruits" },
      { slug: "imported-fruits", nameBn: "Imported Fruits", nameEn: "Imported Fruits" },
      { slug: "citrus-berries", nameBn: "Citrus & Berries", nameEn: "Citrus & Berries" },
    ],
  },
  {
    id: "cat-rice-grains",
    slug: "rice-and-staples",
    nameBn: "Rice, Lentils & Staples",
    nameEn: "Rice, Lentils & Staples",
    descriptionBn: "Aromatic Dinajpur rice, organic lentils, flour & pantry essentials",
    descriptionEn: "Aromatic Dinajpur rice, organic lentils, flour & pantry essentials",
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    itemCount: 64,
    subcategories: [
      { slug: "premium-rice", nameBn: "Aromatic & Fine Rice", nameEn: "Aromatic & Fine Rice" },
      { slug: "lentils-dal", nameBn: "Organic Lentils", nameEn: "Organic Lentils" },
      { slug: "flour-atta", nameBn: "Atta & Flour", nameEn: "Atta & Flour" },
    ],
  },
  {
    id: "cat-oil-ghee",
    slug: "oil-and-ghee",
    nameBn: "Oil, Ghee & Spices",
    nameEn: "Oil, Ghee & Spices",
    descriptionBn: "Cold-pressed mustard oil, pure cow ghee and authentic spices",
    descriptionEn: "Cold-pressed mustard oil, pure cow ghee and authentic spices",
    icon: "🫒",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
    itemCount: 48,
    subcategories: [
      { slug: "mustard-oil", nameBn: "Mustard Oil", nameEn: "Mustard Oil" },
      { slug: "pure-ghee", nameBn: "Desi Ghee", nameEn: "Desi Ghee" },
      { slug: "ground-spices", nameBn: "Ground Spices", nameEn: "Ground Spices" },
    ],
  },
  {
    id: "cat-dairy-eggs",
    slug: "dairy-and-eggs",
    nameBn: "Dairy, Curd & Eggs",
    nameEn: "Dairy, Curd & Eggs",
    descriptionBn: "Farm-fresh milk, Bogura sweet curd, organic brown eggs",
    descriptionEn: "Farm-fresh milk, Bogura sweet curd, organic brown eggs",
    icon: "🥛",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    itemCount: 29,
  },
];

export const VENDORS: VendorShop[] = [
  {
    id: "vendor-green-grocer",
    slug: "green-grocer-bd",
    nameBn: "Green Grocer BD",
    nameEn: "Green Grocer BD",
    taglineBn: "Your trusted farm-to-table organic produce partner",
    taglineEn: "Your trusted farm-to-table organic produce partner",
    logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200&auto=format&fit=crop&q=80",
    rating: 4.9,
    reviewsCount: 184,
    locationBn: "Savar, Dhaka",
    locationEn: "Savar, Dhaka",
    joinedYear: 2023,
    totalProducts: 48,
    verified: true,
    badgeBn: "🏆 Top Rated Seller",
    badgeEn: "🏆 Top Rated Seller",
  },
  {
    id: "vendor-padma-fish",
    slug: "padma-fish-house",
    nameBn: "Padma River Fish Supply",
    nameEn: "Padma River Fish Supply",
    taglineBn: "Daily fresh catch from Chandpur & Padma riverbanks",
    taglineEn: "Daily fresh catch from Chandpur & Padma riverbanks",
    logo: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1506484381205-f7945653044d?w=1200&auto=format&fit=crop&q=80",
    rating: 4.8,
    reviewsCount: 312,
    locationBn: "Chandpur Ghat, Chandpur",
    locationEn: "Chandpur Ghat, Chandpur",
    joinedYear: 2022,
    totalProducts: 32,
    verified: true,
    badgeBn: "🐟 Fresh Fish Certified",
    badgeEn: "🐟 Fresh Fish Certified",
  },
  {
    id: "vendor-bogra-dahi",
    slug: "bogra-shahi-dairy",
    nameBn: "Bogura Shahi Dairy & Sweets",
    nameEn: "Bogura Shahi Dairy & Sweets",
    taglineBn: "Authentic traditional Bogura curd and artisanal cow ghee",
    taglineEn: "Authentic traditional Bogura curd and artisanal cow ghee",
    logo: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=80",
    banner: "https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=1200&auto=format&fit=crop&q=80",
    rating: 5.0,
    reviewsCount: 96,
    locationBn: "Bogura Sadar, Bogura",
    locationEn: "Bogura Sadar, Bogura",
    joinedYear: 2024,
    totalProducts: 18,
    verified: true,
    badgeBn: "⭐ Authentic Heritage",
    badgeEn: "⭐ Authentic Heritage",
  },
];

export const PRODUCTS: Product[] = [
  // 1. Padma Ilish
  {
    id: "prod-ilish-padma",
    slug: "padma-fresh-ilish-fish",
    nameBn: "Fresh Padma River Hilsa Fish (1kg+ size)",
    nameEn: "Fresh Padma River Hilsa Fish (1kg+ size)",
    descriptionBn: "Premium whole silver Hilsa harvested from the Chandpur confluence of Padma river. Unmatched authentic aroma, rich oily texture and peak freshness delivered in pristine condition.",
    descriptionEn: "Premium whole silver Hilsa harvested from the Chandpur confluence of Padma river. Unmatched authentic aroma, rich oily texture and peak freshness delivered in pristine condition.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "Fish & Meat",
    categoryNameEn: "Fish & Meat",
    subcategorySlug: "fresh-river-fish",
    basePrice: 1450,
    comparePrice: 1650,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.8, unit: "kg", labelBn: "800g (Medium)", labelEn: "800g (Medium)", multiplier: 0.8 },
      { value: 1.0, unit: "kg", labelBn: "1 kg (Standard)", labelEn: "1 kg (Standard)", multiplier: 1.0, popular: true },
      { value: 1.2, unit: "kg", labelBn: "1.2 kg (Large)", labelEn: "1.2 kg (Large)", multiplier: 1.25 },
      { value: 1.5, unit: "kg", labelBn: "1.5 kg (King Size)", labelEn: "1.5 kg (King Size)", multiplier: 1.6 },
    ],
    tieredPricing: [
      { minQty: 2, pricePerUnit: 1400, discountPercent: 4, labelBn: "2kg+ at ৳1400/kg", labelEn: "2kg+ at ৳1400/kg" },
      { minQty: 5, pricePerUnit: 1320, discountPercent: 9, labelBn: "5kg+ at ৳1320/kg", labelEn: "5kg+ at ৳1320/kg" },
    ],
    stock: 28,
    images: [
      "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 12,
    originBn: "Chandpur River Estuary, Padma River",
    originEn: "Chandpur River Estuary, Padma River",
    freshnessGuaranteeBn: "Harvested at dawn, same-day delivery",
    freshnessGuaranteeEn: "Harvested at dawn, same-day delivery",
    nutritionInfo: {
      calories: "285 kcal",
      protein: "22.5g",
      carbs: "0.2g",
      fat: "19.4g (Omega-3 Rich)",
    },
    storageTipsBn: "Rub with light salt and freeze immediately to preserve maximum aroma.",
    storageTipsEn: "Rub with light salt and freeze immediately to preserve maximum aroma.",
    rating: 4.9,
    reviewsCount: 88,
    vendorId: "vendor-padma-fish",
    vendorNameBn: "Padma River Fish Supply",
    vendorNameEn: "Padma River Fish Supply",
    vendorSlug: "padma-fish-house",
    isOfficialTatka: false,
    sku: "FISH-ILISH-001",
  },

  // 2. Organic Tomato
  {
    id: "prod-tomato-organic",
    slug: "organic-red-tomatoes",
    nameBn: "Organic Red Farm Tomatoes (Pesticide Free)",
    nameEn: "Organic Red Farm Tomatoes (Pesticide Free)",
    descriptionBn: "Plump, naturally vine-ripened red tomatoes picked daily from organic farms in Savar. Juicy and nutrient-dense with zero chemical ripening agents.",
    descriptionEn: "Plump, naturally vine-ripened red tomatoes picked daily from organic farms in Savar. Juicy and nutrient-dense with zero chemical ripening agents.",
    categorySlug: "vegetables",
    categoryNameBn: "Fresh Vegetables",
    categoryNameEn: "Fresh Vegetables",
    subcategorySlug: "daily-veg",
    basePrice: 65,
    comparePrice: 80,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "250g", labelEn: "250g", multiplier: 0.25 },
      { value: 0.5, unit: "kg", labelBn: "500g", labelEn: "500g", multiplier: 0.5 },
      { value: 1.0, unit: "kg", labelBn: "1 kg", labelEn: "1 kg", multiplier: 1.0, popular: true },
      { value: 2.0, unit: "kg", labelBn: "2 kg", labelEn: "2 kg", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelBn: "5 kg (Family Pack)", labelEn: "5 kg (Family Pack)", multiplier: 4.8 },
    ],
    tieredPricing: [
      { minQty: 3, pricePerUnit: 60, discountPercent: 8, labelBn: "3kg+ at ৳60/kg", labelEn: "3kg+ at ৳60/kg" },
      { minQty: 10, pricePerUnit: 52, discountPercent: 20, labelBn: "10kg+ at ৳52/kg", labelEn: "10kg+ at ৳52/kg" },
    ],
    stock: 150,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1546470427-e26264be0b11?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 18,
    originBn: "Savar & Narsingdi Organic Farms",
    originEn: "Savar & Narsingdi Organic Farms",
    freshnessGuaranteeBn: "Fresh morning harvest",
    freshnessGuaranteeEn: "Fresh morning harvest",
    nutritionInfo: {
      calories: "18 kcal",
      protein: "0.9g",
      carbs: "3.9g",
      fat: "0.2g (Lycopene Rich)",
    },
    storageTipsBn: "Keep at cool room temperature for the best natural sweetness.",
    storageTipsEn: "Keep at cool room temperature for the best natural sweetness.",
    rating: 4.8,
    reviewsCount: 142,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "VEG-TOMATO-002",
  },

  // 3. Kataribhog Rice (Official Tatka Stock)
  {
    id: "prod-rice-kataribhog",
    slug: "dinajpur-kataribhog-aromatic-rice",
    nameBn: "Dinajpur Premium Kataribhog Aromatic Rice",
    nameEn: "Dinajpur Premium Kataribhog Aromatic Rice",
    descriptionBn: "Authentic, naturally aged aromatic Kataribhog grain from Dinajpur. Extremely fluffy, pristine and free from industrial wax or artificial polish.",
    descriptionEn: "Authentic, naturally aged aromatic Kataribhog grain from Dinajpur. Extremely fluffy, pristine and free from industrial wax or artificial polish.",
    categorySlug: "rice-and-staples",
    categoryNameBn: "Rice, Lentils & Staples",
    categoryNameEn: "Rice, Lentils & Staples",
    basePrice: 110,
    comparePrice: 125,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "1 kg", labelEn: "1 kg", multiplier: 1.0 },
      { value: 2.0, unit: "kg", labelBn: "2 kg", labelEn: "2 kg", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelBn: "5 kg Bag", labelEn: "5 kg Bag", multiplier: 4.9, popular: true },
      { value: 25.0, unit: "kg", labelBn: "25 kg Sack (Wholesale)", labelEn: "25 kg Sack (Wholesale)", multiplier: 23.5 },
    ],
    tieredPricing: [
      { minQty: 5, pricePerUnit: 105, discountPercent: 5, labelBn: "5kg+ at ৳105/kg", labelEn: "5kg+ at ৳105/kg" },
      { minQty: 25, pricePerUnit: 98, discountPercent: 11, labelBn: "25kg+ at ৳98/kg", labelEn: "25kg+ at ৳98/kg" },
    ],
    stock: 500,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    originBn: "Birol, Dinajpur",
    originEn: "Birol, Dinajpur",
    freshnessGuaranteeBn: "New season harvest, aged naturally",
    freshnessGuaranteeEn: "New season harvest, aged naturally",
    nutritionInfo: {
      calories: "360 kcal",
      protein: "7.1g",
      carbs: "79.0g",
      fat: "0.6g",
    },
    rating: 4.9,
    reviewsCount: 64,
    vendorNameBn: "Tatka Bazar Official",
    vendorNameEn: "Tatka Bazar Official",
    vendorSlug: "tatka-bazar-official",
    isOfficialTatka: true,
    sku: "GRAIN-KATARI-003",
  },

  // 4. Pure Gawa Ghee
  {
    id: "prod-bogra-ghee",
    slug: "pure-gawa-ghee-bogura",
    nameBn: "Pure Desi Cow Ghee (Traditional Bogura)",
    nameEn: "Pure Desi Cow Ghee (Traditional Bogura)",
    descriptionBn: "Artisanal golden cow ghee churned from fresh farm milk butter in Bogura. Natural grainy texture, heavenly aroma, and 100% pure guarantee.",
    descriptionEn: "Artisanal golden cow ghee churned from fresh farm milk butter in Bogura. Natural grainy texture, heavenly aroma, and 100% pure guarantee.",
    categorySlug: "oil-and-ghee",
    categoryNameBn: "Oil, Ghee & Spices",
    categoryNameEn: "Oil, Ghee & Spices",
    basePrice: 1350,
    comparePrice: 1500,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "250g Glass Jar", labelEn: "250g Glass Jar", multiplier: 0.28 },
      { value: 0.5, unit: "kg", labelBn: "500g Glass Jar", labelEn: "500g Glass Jar", multiplier: 0.52, popular: true },
      { value: 1.0, unit: "kg", labelBn: "1 kg Premium Pot", labelEn: "1 kg Premium Pot", multiplier: 1.0 },
    ],
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    originBn: "Sherpur, Bogura",
    originEn: "Sherpur, Bogura",
    freshnessGuaranteeBn: "Freshly churned batch",
    freshnessGuaranteeEn: "Freshly churned batch",
    nutritionInfo: {
      calories: "884 kcal",
      protein: "0.2g",
      carbs: "0g",
      fat: "99.5g (Rich in Vitamin A, D, E)",
    },
    rating: 5.0,
    reviewsCount: 96,
    vendorId: "vendor-bogra-dahi",
    vendorNameBn: "Bogura Shahi Dairy & Sweets",
    vendorNameEn: "Bogura Shahi Dairy & Sweets",
    vendorSlug: "bogra-shahi-dairy",
    isOfficialTatka: false,
    sku: "DAIRY-GHEE-004",
  },

  // 5. Fresh Rui Fish
  {
    id: "prod-rui-fish",
    slug: "fresh-rui-fish-whole-cut",
    nameBn: "Fresh Local Rui Fish (Cleaned & Cut)",
    nameEn: "Fresh Local Rui Fish (Cleaned & Cut)",
    descriptionBn: "Live fresh sweet-water Rui fish sourced from Meghna river basin. Customized descaling and curry-cut preparation before immediate iced dispatch.",
    descriptionEn: "Live fresh sweet-water Rui fish sourced from Meghna river basin. Customized descaling and curry-cut preparation before immediate iced dispatch.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "Fish & Meat",
    categoryNameEn: "Fish & Meat",
    subcategorySlug: "fresh-river-fish",
    basePrice: 420,
    comparePrice: 480,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "1 kg (Curry Cut)", labelEn: "1 kg (Curry Cut)", multiplier: 1.0 },
      { value: 1.5, unit: "kg", labelBn: "1.5 kg (Whole Fish)", labelEn: "1.5 kg (Whole Fish)", multiplier: 1.5, popular: true },
      { value: 2.5, unit: "kg", labelBn: "2.5 kg (Giant Rui)", labelEn: "2.5 kg (Giant Rui)", multiplier: 2.45 },
    ],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80",
    ],
    isDailyBazar: true,
    flashDiscount: 14,
    originBn: "Meghna River & Kishoreganj Haor",
    originEn: "Meghna River & Kishoreganj Haor",
    freshnessGuaranteeBn: "Daily live catch",
    freshnessGuaranteeEn: "Daily live catch",
    rating: 4.7,
    reviewsCount: 52,
    vendorId: "vendor-padma-fish",
    vendorNameBn: "Padma River Fish Supply",
    vendorNameEn: "Padma River Fish Supply",
    vendorSlug: "padma-fish-house",
    isOfficialTatka: false,
    sku: "FISH-RUI-005",
  },

  // 6. Fresh Lal Shak (Red Spinach)
  {
    id: "prod-lal-shak",
    slug: "fresh-lal-shak-organic",
    nameBn: "Fresh Desi Red Spinach (Lal Shak)",
    nameEn: "Fresh Desi Red Spinach (Lal Shak)",
    descriptionBn: "Tender, iron-rich crimson leafy spinach harvested freshly at sunrise. Rich in vitamins and zero pesticide residues.",
    descriptionEn: "Tender, iron-rich crimson leafy spinach harvested freshly at sunrise. Rich in vitamins and zero pesticide residues.",
    categorySlug: "vegetables",
    categoryNameBn: "Fresh Vegetables",
    categoryNameEn: "Fresh Vegetables",
    subcategorySlug: "leafy-greens",
    basePrice: 35,
    comparePrice: 45,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.25, unit: "kg", labelBn: "250g (1 Bundle)", labelEn: "250g (1 Bundle)", multiplier: 0.25 },
      { value: 0.5, unit: "kg", labelBn: "500g (2 Bundles)", labelEn: "500g (2 Bundles)", multiplier: 0.5, popular: true },
      { value: 1.0, unit: "kg", labelBn: "1 kg (Family Pack)", labelEn: "1 kg (Family Pack)", multiplier: 0.95 },
    ],
    stock: 90,
    images: [
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isDailyBazar: true,
    flashDiscount: 20,
    originBn: "Keraniganj & Munshiganj Organic Farms",
    originEn: "Keraniganj & Munshiganj Organic Farms",
    freshnessGuaranteeBn: "Tender morning harvest",
    freshnessGuaranteeEn: "Tender morning harvest",
    nutritionInfo: {
      calories: "23 kcal",
      protein: "2.2g",
      carbs: "3.8g",
      fat: "0.3g (Iron & Vitamin A rich)",
    },
    rating: 4.9,
    reviewsCount: 77,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "VEG-LALSHAK-006",
  },

  // 7. Pure Kachi Ghani Mustard Oil
  {
    id: "prod-mustard-oil-teer",
    slug: "pure-kachi-ghani-mustard-oil-1-litre",
    nameBn: "Pure Kachi Ghani Mustard Oil (Cold Pressed, 1 Litre)",
    nameEn: "Pure Kachi Ghani Mustard Oil (Cold Pressed, 1 Litre)",
    descriptionBn: "100% pure cold-pressed mustard oil extracted from premium Bangladeshi mustard seeds. Pungent aroma and rich authentic flavor, perfect for traditional Hilsa bhapa, bhorta and pickles.",
    descriptionEn: "100% pure cold-pressed mustard oil extracted from premium Bangladeshi mustard seeds. Pungent aroma and rich authentic flavor, perfect for traditional Hilsa bhapa, bhorta and pickles.",
    categorySlug: "oil-and-ghee",
    categoryNameBn: "Oil, Ghee & Spices",
    categoryNameEn: "Oil, Ghee & Spices",
    subcategorySlug: "mustard-oil",
    basePrice: 340,
    comparePrice: 380,
    baseUnit: "liter",
    pricingType: "fixed",
    stock: 120,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    flashDiscount: 10,
    originBn: "Natore & Pabna Mustard Mills",
    originEn: "Natore & Pabna Mustard Mills",
    freshnessGuaranteeBn: "100% Pure Cold Pressed, Zero Additives",
    freshnessGuaranteeEn: "100% Pure Cold Pressed, Zero Additives",
    nutritionInfo: {
      calories: "884 kcal",
      protein: "0g",
      carbs: "0g",
      fat: "100g (Rich in Omega-3 & 6)",
    },
    storageTipsBn: "Store in a cool, dark pantry away from direct heat or sunlight.",
    storageTipsEn: "Store in a cool, dark pantry away from direct heat or sunlight.",
    rating: 4.9,
    reviewsCount: 114,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: true,
    sku: "OIL-MUSTARD-007",
    brandName: "Tatka Select",
    brandSlug: "tatka-select",
  },

  // 8. Desi Sonali Country Chicken
  {
    id: "prod-chicken-sonali",
    slug: "desi-free-range-sonali-chicken-1kg",
    nameBn: "Desi Free-Range Sonali Chicken (Whole Cleaned, 1kg+)",
    nameEn: "Desi Free-Range Sonali Chicken (Whole Cleaned, 1kg+)",
    descriptionBn: "Naturally reared free-range Sonali country chicken from pastoral farms. Lean, firm meat with rich natural broth flavor, 100% antibiotic-residue free and freshly processed upon order.",
    descriptionEn: "Naturally reared free-range Sonali country chicken from pastoral farms. Lean, firm meat with rich natural broth flavor, 100% antibiotic-residue free and freshly processed upon order.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "Fish & Meat",
    categoryNameEn: "Fish & Meat",
    subcategorySlug: "desi-chicken",
    basePrice: 380,
    comparePrice: 420,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.8, unit: "kg", labelBn: "800g (Medium)", labelEn: "800g (Medium)", multiplier: 0.8 },
      { value: 1.0, unit: "kg", labelBn: "1 kg (Standard)", labelEn: "1 kg (Standard)", multiplier: 1.0, popular: true },
      { value: 1.2, unit: "kg", labelBn: "1.2 kg (Large)", labelEn: "1.2 kg (Large)", multiplier: 1.2 },
      { value: 1.5, unit: "kg", labelBn: "1.5 kg (Family Pack)", labelEn: "1.5 kg (Family Pack)", multiplier: 1.5 },
    ],
    tieredPricing: [
      { minQty: 3, pricePerUnit: 360, discountPercent: 5, labelBn: "3kg+ at ৳360/kg", labelEn: "3kg+ at ৳360/kg" },
    ],
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 10,
    originBn: "Narsingdi & Gazipur Pastoral Farms",
    originEn: "Narsingdi & Gazipur Pastoral Farms",
    freshnessGuaranteeBn: "Freshly dressed after morning order, ice-packed",
    freshnessGuaranteeEn: "Freshly dressed after morning order, ice-packed",
    nutritionInfo: {
      calories: "215 kcal",
      protein: "27.3g",
      carbs: "0g",
      fat: "8.5g",
    },
    storageTipsBn: "Store in freezer at -18°C or cook within 24 hours of delivery.",
    storageTipsEn: "Store in freezer at -18°C or cook within 24 hours of delivery.",
    rating: 4.8,
    reviewsCount: 78,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "MEAT-CHICK-008",
  },

  // 9. Fresh River Tiger Prawn / Bagda Chingri
  {
    id: "prod-prawn-bagda",
    slug: "fresh-river-tiger-prawn-bagda-chingri-500g",
    nameBn: "Fresh River Tiger Prawn / Bagda Chingri (500g Pack)",
    nameEn: "Fresh River Tiger Prawn / Bagda Chingri (500g Pack)",
    descriptionBn: "Succulent, naturally sweet river tiger prawns harvested from the brackish waters of Satkhira. Firm white meat, cleaned and deveined upon request, perfect for Malaicurry or roast.",
    descriptionEn: "Succulent, naturally sweet river tiger prawns harvested from the brackish waters of Satkhira. Firm white meat, cleaned and deveined upon request, perfect for Malaicurry or roast.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "Fish & Meat",
    categoryNameEn: "Fish & Meat",
    subcategorySlug: "sea-fish",
    basePrice: 650,
    comparePrice: 720,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.5, unit: "kg", labelBn: "500g Pack (15-18 pcs)", labelEn: "500g Pack (15-18 pcs)", multiplier: 0.5, popular: true },
      { value: 1.0, unit: "kg", labelBn: "1 kg Mega Pack", labelEn: "1 kg Mega Pack", multiplier: 1.0 },
    ],
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    flashDiscount: 10,
    originBn: "Satkhira Estuary & Khulna",
    originEn: "Satkhira Estuary & Khulna",
    freshnessGuaranteeBn: "Caught at dawn, delivered in chilling ice box",
    freshnessGuaranteeEn: "Caught at dawn, delivered in chilling ice box",
    nutritionInfo: {
      calories: "106 kcal",
      protein: "24.0g",
      carbs: "0.9g",
      fat: "1.7g",
    },
    rating: 4.9,
    reviewsCount: 62,
    vendorId: "vendor-padma-fish",
    vendorNameBn: "Padma River Fish Supply",
    vendorNameEn: "Padma River Fish Supply",
    vendorSlug: "padma-fish-house",
    isOfficialTatka: false,
    sku: "FISH-PRAWN-009",
  },

  // 10. Rajshahi Premium Himsagar Mango
  {
    id: "prod-mango-himsagar",
    slug: "rajshahi-premium-himsagar-mango-1kg",
    nameBn: "Rajshahi Premium Himsagar Mango (100% Formalin-Free, 1kg)",
    nameEn: "Rajshahi Premium Himsagar Mango (100% Formalin-Free, 1kg)",
    descriptionBn: "World-famous GI-tagged Himsagar mangoes tree-ripened in Rajshahi orchards. Intensely sweet, fibreless silky golden pulp with zero artificial carbide or chemical ripening agents.",
    descriptionEn: "World-famous GI-tagged Himsagar mangoes tree-ripened in Rajshahi orchards. Intensely sweet, fibreless silky golden pulp with zero artificial carbide or chemical ripening agents.",
    categorySlug: "fruits",
    categoryNameBn: "Fresh Fruits",
    categoryNameEn: "Fresh Fruits",
    subcategorySlug: "seasonal-fruits",
    basePrice: 160,
    comparePrice: 190,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "1 kg", labelEn: "1 kg", multiplier: 1.0 },
      { value: 2.0, unit: "kg", labelBn: "2 kg Pack", labelEn: "2 kg Pack", multiplier: 2.0, popular: true },
      { value: 5.0, unit: "kg", labelBn: "5 kg Crate", labelEn: "5 kg Crate", multiplier: 4.8 },
    ],
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 15,
    originBn: "Bagha, Rajshahi Orchards",
    originEn: "Bagha, Rajshahi Orchards",
    freshnessGuaranteeBn: "Tree-ripened, 100% Formalin-Free Guaranteed",
    freshnessGuaranteeEn: "Tree-ripened, 100% Formalin-Free Guaranteed",
    nutritionInfo: {
      calories: "60 kcal",
      protein: "0.8g",
      carbs: "15.0g",
      fat: "0.4g (Vitamin C & A Rich)",
    },
    rating: 5.0,
    reviewsCount: 145,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: true,
    sku: "FRUIT-MANGO-010",
  },

  // 11. Traditional Bogura Shahi Mishti Doi
  {
    id: "prod-sweet-curd-bogra",
    slug: "traditional-bogura-special-shahi-mishti-doi-500g",
    nameBn: "Traditional Bogura Special Shahi Mishti Doi (500g Clay Pot)",
    nameEn: "Traditional Bogura Special Shahi Mishti Doi (500g Clay Pot)",
    descriptionBn: "Centuries-old heritage sweet curd slowly simmered and caramelised in traditional earthen clay pots in Bogura. Velvety caramelized top, thick natural texture, and heavenly sweetness.",
    descriptionEn: "Centuries-old heritage sweet curd slowly simmered and caramelised in traditional earthen clay pots in Bogura. Velvety caramelized top, thick natural texture, and heavenly sweetness.",
    categorySlug: "dairy-and-eggs",
    categoryNameBn: "Dairy, Curd & Eggs",
    categoryNameEn: "Dairy, Curd & Eggs",
    basePrice: 190,
    comparePrice: 220,
    baseUnit: "piece",
    pricingType: "fixed",
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    flashDiscount: 12,
    originBn: "Sherpur, Bogura",
    originEn: "Sherpur, Bogura",
    freshnessGuaranteeBn: "Direct from Bogura, refrigerated cold-chain",
    freshnessGuaranteeEn: "Direct from Bogura, refrigerated cold-chain",
    nutritionInfo: {
      calories: "160 kcal",
      protein: "4.8g",
      carbs: "24.0g",
      fat: "5.2g (Calcium Rich)",
    },
    rating: 5.0,
    reviewsCount: 92,
    vendorId: "vendor-bogra-dahi",
    vendorNameBn: "Bogura Shahi Dairy & Sweets",
    vendorNameEn: "Bogura Shahi Dairy & Sweets",
    vendorSlug: "bogra-shahi-dairy",
    isOfficialTatka: false,
    sku: "DAIRY-DOI-011",
  },

  // 12. Premium Grass-Fed Bengal Beef
  {
    id: "prod-beef-premium",
    slug: "premium-grass-fed-bengal-beef-curry-cut-1kg",
    nameBn: "Premium Grass-Fed Bengal Beef (Curry Cut, 1kg)",
    nameEn: "Premium Grass-Fed Bengal Beef (Curry Cut, 1kg)",
    descriptionBn: "Tender, fresh grass-fed local beef sourced from certified veterinary-inspected farms. Perfectly balanced meat with marrow bone for rich traditional Bengali beef bhuna.",
    descriptionEn: "Tender, fresh grass-fed local beef sourced from certified veterinary-inspected farms. Perfectly balanced meat with marrow bone for rich traditional Bengali beef bhuna.",
    categorySlug: "fish-and-meat",
    categoryNameBn: "Fish & Meat",
    categoryNameEn: "Fish & Meat",
    subcategorySlug: "mutton-beef",
    basePrice: 780,
    comparePrice: 850,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1.0, unit: "kg", labelBn: "1 kg (Standard Curry Cut)", labelEn: "1 kg (Standard Curry Cut)", multiplier: 1.0, popular: true },
      { value: 2.0, unit: "kg", labelBn: "2 kg Pack", labelEn: "2 kg Pack", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelBn: "5 kg Family Feast", labelEn: "5 kg Family Feast", multiplier: 4.85 },
    ],
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    flashDiscount: 8,
    originBn: "Pabna & Sirajganj Dairy Belt",
    originEn: "Pabna & Sirajganj Dairy Belt",
    freshnessGuaranteeBn: "100% Halal slaughtered, freshly prepared daily",
    freshnessGuaranteeEn: "100% Halal slaughtered, freshly prepared daily",
    nutritionInfo: {
      calories: "250 kcal",
      protein: "26.0g",
      carbs: "0g",
      fat: "15.0g (Iron Rich)",
    },
    rating: 4.8,
    reviewsCount: 84,
    vendorNameBn: "Tatka Bazar Meat Hub",
    vendorNameEn: "Tatka Bazar Meat Hub",
    vendorSlug: "tatka-bazar-meat-hub",
    isOfficialTatka: true,
    sku: "MEAT-BEEF-012",
  },

  // 13. Fresh Green Chili & Coriander Combo
  {
    id: "prod-green-chili-coriander",
    slug: "fresh-desi-green-chili-fragrant-coriander-combo-250g",
    nameBn: "Fresh Desi Green Chili & Fragrant Coriander Combo (250g)",
    nameEn: "Fresh Desi Green Chili & Fragrant Coriander Combo (250g)",
    descriptionBn: "Crisp, pungent local green chilies paired with vibrant, intensely aromatic freshly uprooted coriander leaves from Munshiganj riverbanks.",
    descriptionEn: "Crisp, pungent local green chilies paired with vibrant, intensely aromatic freshly uprooted coriander leaves from Munshiganj riverbanks.",
    categorySlug: "vegetables",
    categoryNameBn: "Fresh Vegetables",
    categoryNameEn: "Fresh Vegetables",
    subcategorySlug: "salad-items",
    basePrice: 45,
    comparePrice: 55,
    baseUnit: "packet",
    pricingType: "fixed",
    stock: 100,
    images: [
      "https://images.unsplash.com/photo-1588879460618-924b170e5917?w=800&auto=format&fit=crop&q=80",
    ],
    originBn: "Munshiganj Riverbank Farms",
    originEn: "Munshiganj Riverbank Farms",
    freshnessGuaranteeBn: "Morning harvest, crisp and aromatic",
    freshnessGuaranteeEn: "Morning harvest, crisp and aromatic",
    rating: 4.9,
    reviewsCount: 56,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "VEG-CHILI-013",
  },

  // 14. 100% Pure Sundarbans Wild Honey
  {
    id: "prod-honey-sundarbans",
    slug: "100-pure-sundarbans-wild-mangrove-honey-500g",
    nameBn: "100% Pure Sundarbans Wild Mangrove Honey (500g Glass Jar)",
    nameEn: "100% Pure Sundarbans Wild Mangrove Honey (500g Glass Jar)",
    descriptionBn: "Raw, unpasteurized forest honey gathered by traditional Mawali beekeepers from the deep mangrove forest of Sundarbans. Packed with natural antioxidants, pollen, and distinctive wildflower aroma.",
    descriptionEn: "Raw, unpasteurized forest honey gathered by traditional Mawali beekeepers from the deep mangrove forest of Sundarbans. Packed with natural antioxidants, pollen, and distinctive wildflower aroma.",
    categorySlug: "oil-and-ghee",
    categoryNameBn: "Oil, Ghee & Spices",
    categoryNameEn: "Oil, Ghee & Spices",
    basePrice: 550,
    comparePrice: 650,
    baseUnit: "piece",
    pricingType: "fixed",
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    originBn: "Sundarbans Mangrove Forest, Satkhira",
    originEn: "Sundarbans Mangrove Forest, Satkhira",
    freshnessGuaranteeBn: "100% Raw Wild Honey, Zero Sugar Feed",
    freshnessGuaranteeEn: "100% Raw Wild Honey, Zero Sugar Feed",
    nutritionInfo: {
      calories: "304 kcal",
      protein: "0.3g",
      carbs: "82.4g",
      fat: "0g (Natural Enzymes Rich)",
    },
    rating: 5.0,
    reviewsCount: 48,
    vendorNameBn: "Tatka Bazar Direct",
    vendorNameEn: "Tatka Bazar Direct",
    vendorSlug: "tatka-bazar-direct",
    isOfficialTatka: true,
    sku: "STAPLE-HONEY-014",
  },

  // 15. Farm-Fresh Desi Free-Range Brown Eggs
  {
    id: "prod-egg-organic-brown",
    slug: "farm-fresh-desi-free-range-brown-eggs-pack-of-12",
    nameBn: "Farm-Fresh Desi Free-Range Brown Eggs (Pack of 12)",
    nameEn: "Farm-Fresh Desi Free-Range Brown Eggs (Pack of 12)",
    descriptionBn: "Farm-fresh nutritious brown eggs from pastured country hens fed on organic grains. Rich golden-orange yolks with high protein and vitamin D content.",
    descriptionEn: "Farm-fresh nutritious brown eggs from pastured country hens fed on organic grains. Rich golden-orange yolks with high protein and vitamin D content.",
    categorySlug: "dairy-and-eggs",
    categoryNameBn: "Dairy, Curd & Eggs",
    categoryNameEn: "Dairy, Curd & Eggs",
    basePrice: 165,
    comparePrice: 180,
    baseUnit: "dozen",
    pricingType: "fixed",
    stock: 90,
    images: [
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isDailyBazar: true,
    originBn: "Gazipur Pasture Poultry",
    originEn: "Gazipur Pasture Poultry",
    freshnessGuaranteeBn: "Collected this morning, unwashed natural shell",
    freshnessGuaranteeEn: "Collected this morning, unwashed natural shell",
    nutritionInfo: {
      calories: "72 kcal (per egg)",
      protein: "6.3g",
      carbs: "0.4g",
      fat: "4.8g (Vitamin D Rich)",
    },
    rating: 4.9,
    reviewsCount: 118,
    vendorId: "vendor-green-grocer",
    vendorNameBn: "Green Grocer BD",
    vendorNameEn: "Green Grocer BD",
    vendorSlug: "green-grocer-bd",
    isOfficialTatka: false,
    sku: "DAIRY-EGG-015",
  },
];

export const BRANCHES: Branch[] = [
  {
    id: "branch-dhanmondi",
    nameBn: "Dhanmondi Express Hub",
    nameEn: "Dhanmondi Express Hub",
    areaBn: "Dhanmondi, Dhaka",
    areaEn: "Dhanmondi, Dhaka",
    addressBn: "House 27, Road 8/A, Dhanmondi R/A, Dhaka 1209",
    addressEn: "House 27, Road 8/A, Dhanmondi R/A, Dhaka 1209",
    phone: "01701-111000",
    deliveryTimeBn: "30-45 mins",
    deliveryTimeEn: "30-45 mins",
    isOpen: true,
  },
  {
    id: "branch-gulshan",
    nameBn: "Gulshan 2 Flagship Hub",
    nameEn: "Gulshan 2 Flagship Hub",
    areaBn: "Gulshan & Banani, Dhaka",
    areaEn: "Gulshan & Banani, Dhaka",
    addressBn: "Plot 12, Road 104, Gulshan 2, Dhaka 1212",
    addressEn: "Plot 12, Road 104, Gulshan 2, Dhaka 1212",
    phone: "01701-222000",
    deliveryTimeBn: "30-45 mins",
    deliveryTimeEn: "30-45 mins",
    isOpen: true,
  },
  {
    id: "branch-uttara",
    nameBn: "Uttara Express Hub",
    nameEn: "Uttara Express Hub",
    areaBn: "Uttara (Sectors 1-18), Dhaka",
    areaEn: "Uttara (Sectors 1-18), Dhaka",
    addressBn: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka 1230",
    addressEn: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka 1230",
    phone: "01701-333000",
    deliveryTimeBn: "40-50 mins",
    deliveryTimeEn: "40-50 mins",
    isOpen: true,
  },
  {
    id: "branch-mirpur",
    nameBn: "Mirpur Central Hub",
    nameEn: "Mirpur Central Hub",
    areaBn: "Mirpur 1-14 & Pallabi, Dhaka",
    areaEn: "Mirpur 1-14 & Pallabi, Dhaka",
    addressBn: "Near Mirpur 10 Circle, Dhaka 1216",
    addressEn: "Near Mirpur 10 Circle, Dhaka 1216",
    phone: "01701-444000",
    deliveryTimeBn: "35-45 mins",
    deliveryTimeEn: "35-45 mins",
    isOpen: true,
  },
  {
    id: "branch-ctg",
    nameBn: "Chattogram GEC Hub",
    nameEn: "Chattogram GEC Hub",
    areaBn: "GEC, Nasirabad & Khulshi, Chattogram",
    areaEn: "GEC, Nasirabad & Khulshi, Chattogram",
    addressBn: "GEC Circle, O.R. Nizam Road, Chattogram 4000",
    addressEn: "GEC Circle, O.R. Nizam Road, Chattogram 4000",
    phone: "01701-555000",
    deliveryTimeBn: "45-60 mins",
    deliveryTimeEn: "45-60 mins",
    isOpen: true,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "rev-1",
    userName: "Tanveer Hassan",
    userLocation: "Dhanmondi, Dhaka",
    rating: 5,
    date: "August 21, 2026",
    commentBn: "The Padma Hilsa was extraordinarily fresh! Ordered early morning and received before 8:30 AM. Superb temperature-controlled packaging.",
    commentEn: "The Padma Hilsa was extraordinarily fresh! Ordered early morning and received before 8:30 AM. Superb temperature-controlled packaging.",
    verifiedPurchase: true,
    likes: 38,
    category: "fish",
    productNameBn: "Fresh Padma Hilsa (1.2 kg)",
    productNameEn: "Fresh Padma Hilsa (1.2 kg)",
    userRoleBn: "Gold Member",
    userRoleEn: "Gold Member",
    deliveryTimeBn: "Delivered in 35 mins",
    deliveryTimeEn: "Delivered in 35 mins",
  },
  {
    id: "rev-2",
    userName: "Farzana Haque",
    userLocation: "Gulshan 2, Dhaka",
    rating: 5,
    date: "August 20, 2026",
    commentBn: "The vegetables are 100% organic and fresh as if freshly harvested. Weight-based gram customization is extremely convenient!",
    commentEn: "The vegetables are 100% organic and fresh as if freshly harvested. Weight-based gram customization is extremely convenient!",
    verifiedPurchase: true,
    likes: 42,
    category: "veggies",
    productNameBn: "Organic Fresh Veggie Combo",
    productNameEn: "Organic Fresh Veggie Combo",
    userRoleBn: "Food & Health Trainer",
    userRoleEn: "Food & Health Trainer",
    deliveryTimeBn: "Delivered in 28 mins",
    deliveryTimeEn: "Delivered in 28 mins",
  },
  {
    id: "rev-3",
    userName: "Mahmudur Rahman",
    userLocation: "Uttara Sector 7, Dhaka",
    rating: 5,
    date: "August 19, 2026",
    commentBn: "The aroma of Bogura pure ghee and Dinajpur Kataribhog rice is unmatched. Multi-vendor order splitting worked seamlessly. Top-notch service!",
    commentEn: "The aroma of Bogura pure ghee and Dinajpur Kataribhog rice is unmatched. Multi-vendor order splitting worked seamlessly. Top-notch service!",
    verifiedPurchase: true,
    likes: 56,
    category: "village",
    productNameBn: "Bogura Special Ghee & Kataribhog Rice",
    productNameEn: "Bogura Special Ghee & Kataribhog Rice",
    userRoleBn: "Premium Regular Buyer",
    userRoleEn: "Premium Regular Buyer",
    deliveryTimeBn: "Delivered in 42 mins",
    deliveryTimeEn: "Delivered in 42 mins",
  },
  {
    id: "rev-4",
    userName: "Dr. Nusrat Jahan",
    userLocation: "Banani, Dhaka",
    rating: 5,
    date: "August 18, 2026",
    commentBn: "Regularly order Sundarbans pure raw honey and farm-fresh country eggs for my kids. Their lab-tested hygiene and purity are unmatched.",
    commentEn: "Regularly order Sundarbans pure raw honey and farm-fresh country eggs for my kids. Their lab-tested hygiene and purity are unmatched.",
    verifiedPurchase: true,
    likes: 49,
    category: "village",
    productNameBn: "Sundarbans Raw Honey & Country Eggs",
    productNameEn: "Sundarbans Raw Honey & Country Eggs",
    userRoleBn: "Pediatrician (Doctor)",
    userRoleEn: "Pediatrician (Doctor)",
    deliveryTimeBn: "Delivered in 30 mins",
    deliveryTimeEn: "Delivered in 30 mins",
  },
  {
    id: "rev-5",
    userName: "Engr. Arifur Rahman",
    userLocation: "Mirpur DOHS, Dhaka",
    rating: 5,
    date: "August 16, 2026",
    commentBn: "Ordered between meetings with a single click. Exactly in 25 minutes the rider arrived at the door! Real-time GPS tracking is flawless.",
    commentEn: "Ordered between meetings with a single click. Exactly in 25 minutes the rider arrived at the door! Real-time GPS tracking is flawless.",
    verifiedPurchase: true,
    likes: 64,
    category: "express",
    productNameBn: "Fresh Morning Breakfast Basket & Fruits",
    productNameEn: "Fresh Morning Breakfast Basket & Fruits",
    userRoleBn: "Software Architect",
    userRoleEn: "Software Architect",
    deliveryTimeBn: "25 min Express Delivery",
    deliveryTimeEn: "25 min Express Delivery",
  },
  {
    id: "rev-6",
    userName: "Rubaiya Kamal",
    userLocation: "GEC Circle, Chattogram",
    rating: 5,
    date: "August 15, 2026",
    commentBn: "Fresh giant prawns and Pomfret fish cleaner and fresher than any upscale superstore. Dry-ice sealed packaging is truly 5-star standard!",
    commentEn: "Fresh giant prawns and Pomfret fish cleaner and fresher than any upscale superstore. Dry-ice sealed packaging is truly 5-star standard!",
    verifiedPurchase: true,
    likes: 37,
    category: "fish",
    productNameBn: "Fresh Bay Pomfret & Tiger Prawns",
    productNameEn: "Fresh Bay Pomfret & Tiger Prawns",
    userRoleBn: "Culinary Chef & Influencer",
    userRoleEn: "Culinary Chef & Influencer",
    deliveryTimeBn: "Delivered in 40 mins",
    deliveryTimeEn: "Delivered in 40 mins",
  },
  {
    id: "rev-7",
    userName: "Nadia Chowdhury",
    userLocation: "Baridhara Diplomatic Zone, Dhaka",
    rating: 5,
    date: "August 14, 2026",
    commentBn: "Family is overjoyed receiving chemical-free fresh spinach, bottle gourd, and sweet pumpkin. Kudos to Tatka Bazar for pure organic standards!",
    commentEn: "Family is overjoyed receiving chemical-free fresh spinach, bottle gourd, and sweet pumpkin. Kudos to Tatka Bazar for pure organic standards!",
    verifiedPurchase: true,
    likes: 51,
    category: "veggies",
    productNameBn: "Vitamin Rich Organic Green Basket",
    productNameEn: "Vitamin Rich Organic Green Basket",
    userRoleBn: "Nutrition & Health Specialist",
    userRoleEn: "Nutrition & Health Specialist",
    deliveryTimeBn: "Delivered in 32 mins",
    deliveryTimeEn: "Delivered in 32 mins",
  },
  {
    id: "rev-8",
    userName: "Mehrab Hossain",
    userLocation: "Shantinagar, Dhaka",
    rating: 5,
    date: "August 12, 2026",
    commentBn: "Had sudden guests and ordered meat & sweets in express mode. Unbelievable that everything was delivered flawlessly in just 20 minutes!",
    commentEn: "Had sudden guests and ordered meat & sweets in express mode. Unbelievable that everything was delivered flawlessly in just 20 minutes!",
    verifiedPurchase: true,
    likes: 45,
    category: "express",
    productNameBn: "Fresh Mutton & Bogura Curd",
    productNameEn: "Fresh Mutton & Bogura Curd",
    userRoleBn: "Content Creator & Foodie",
    userRoleEn: "Content Creator & Foodie",
    deliveryTimeBn: "20 min Superfast Delivery",
    deliveryTimeEn: "20 min Superfast Delivery",
  },
];
