// =============================================================================
// Tatka Bazar — Admin Mock Dataset v3.0 (Complete Rich Data)
// =============================================================================

import {
  AdminUser, StaffMember, AdminOrder, AdminProduct, AdminCategory,
  AdminVendor, AdminB2BAccount, AdminRider, AdminBranch, AdminCoupon,
  AdminReview, AuditLogEntry, AdminCustomer,
} from "@/types";

export const INITIAL_ADMIN_USER: AdminUser = {
  id: "admin-super",
  name: "Tamim Khan",
  email: "admin@tatkabazar.com",
  role: "SUPER_ADMIN",
  lastLogin: "Today, 11:45 PM",
};

// ── Staff Members ────────────────────────────────────────────────────────────

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: "staff-1",
    name: "Tamim Khan",
    email: "admin@tatkabazar.com",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    phone: "01700000001",
    address: "House 12, Road 4, Dhanmondi, Dhaka",
    department: "Executive Management",
    assignedBranch: "Dhanmondi Central Hub",
    joinedDate: "1 Jan 2024",
    lastLogin: "Today, 08:30 AM",
    invitedAt: "1 Jan 2024",
    invitedBy: "Founder",
    ordersCollectedToday: 24,
    ordersCollectedLast30Days: 512,
    ordersCollectedLifetime: 2340,
    dailySession: {
      loginTime: "08:30 AM",
      logoutTime: "Active Now",
      activeMinutesToday: 410,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: true,
    },
    kyc: {
      nidNumber: "19942691234567890",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "House 12, Road 4, Dhanmondi, Dhaka",
      permanentAddress: "Village: Charail, Thana: Barguna Sadar, District: Barguna",
      district: "Dhaka",
      thana: "Dhanmondi",
      emergencyContactName: "Kabir Khan (Father)",
      emergencyContactPhone: "01711998877",
      submittedAt: "2 Jan 2024",
      verifiedAt: "2 Jan 2024",
    },
  },
  {
    id: "staff-2",
    name: "Rakib Hossain",
    email: "rakib@tatkabazar.com",
    role: "MANAGER",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    phone: "01711223344",
    address: "Apartment 4B, Sector 7, Uttara, Dhaka",
    department: "Operations & Vendor Coordination",
    assignedBranch: "Uttara Hub",
    joinedDate: "5 Mar 2025",
    lastLogin: "Today, 09:15 AM",
    invitedAt: "5 Mar 2025",
    invitedBy: "Tamim Khan",
    ordersCollectedToday: 19,
    ordersCollectedLast30Days: 420,
    ordersCollectedLifetime: 1680,
    dailySession: {
      loginTime: "09:15 AM",
      logoutTime: "Active Now",
      activeMinutesToday: 365,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: true,
    },
    kyc: {
      nidNumber: "19902699887766554",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "Apartment 4B, Sector 7, Uttara, Dhaka",
      permanentAddress: "Main Road, Feni Sadar, Feni",
      district: "Dhaka",
      thana: "Uttara",
      emergencyContactName: "Nasreen Sultana (Spouse)",
      emergencyContactPhone: "01819223344",
      submittedAt: "6 Mar 2025",
      verifiedAt: "7 Mar 2025",
    },
  },
  {
    id: "staff-3",
    name: "Sadia Islam",
    email: "sadia@tatkabazar.com",
    role: "SUPPORT_STAFF",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    phone: "01811556677",
    address: "Block C, Mirpur 2, Dhaka",
    department: "Customer Service & Dispute",
    assignedBranch: "Mirpur Hub",
    joinedDate: "12 May 2025",
    lastLogin: "Today, 09:00 AM",
    invitedAt: "12 May 2025",
    invitedBy: "Tamim Khan",
    ordersCollectedToday: 14,
    ordersCollectedLast30Days: 310,
    ordersCollectedLifetime: 940,
    dailySession: {
      loginTime: "09:00 AM",
      logoutTime: "05:45 PM",
      activeMinutesToday: 525,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: false,
    },
    kyc: {
      nidNumber: "19972688771122334",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "Block C, Mirpur 2, Dhaka",
      permanentAddress: "Ghoramara, Boalia, Rajshahi",
      district: "Dhaka",
      thana: "Mirpur",
      emergencyContactName: "Anisur Islam (Brother)",
      emergencyContactPhone: "01712334455",
      submittedAt: "13 May 2025",
      verifiedAt: "14 May 2025",
    },
  },
  {
    id: "staff-4",
    name: "Farhan Ahmed",
    email: "farhan@tatkabazar.com",
    role: "DELIVERY_COORDINATOR",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    phone: "01911889900",
    address: "Lane 3, Lalmatia, Mohammadpur, Dhaka",
    department: "Logistics & Dispatch Fleet",
    assignedBranch: "Dhanmondi Hub",
    joinedDate: "20 Jun 2025",
    lastLogin: "Today, 07:30 AM",
    invitedAt: "20 Jun 2025",
    invitedBy: "Rakib Hossain",
    ordersCollectedToday: 32,
    ordersCollectedLast30Days: 680,
    ordersCollectedLifetime: 2150,
    dailySession: {
      loginTime: "07:30 AM",
      logoutTime: "Active Now",
      activeMinutesToday: 470,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: true,
    },
    kyc: {
      nidNumber: "19932677665544332",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "Lane 3, Lalmatia, Dhaka",
      permanentAddress: "Amtoli, Barguna District",
      district: "Dhaka",
      thana: "Mohammadpur",
      emergencyContactName: "Jashim Ahmed (Uncle)",
      emergencyContactPhone: "01815667788",
      submittedAt: "21 Jun 2025",
      verifiedAt: "22 Jun 2025",
    },
  },
  {
    id: "staff-5",
    name: "Nusrat Jahan",
    email: "nusrat@tatkabazar.com",
    role: "INVENTORY_STAFF",
    status: "PENDING",
    kycStatus: "SUBMITTED",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    phone: "01722334455",
    address: "House 28, Road 11, Banani, Dhaka",
    department: "Warehousing & Perishables",
    assignedBranch: "Gulshan Hub",
    joinedDate: "7 Sep 2026",
    lastLogin: "Pending Verification",
    invitedAt: "7 Sep 2026",
    invitedBy: "Tamim Khan",
    ordersCollectedToday: 0,
    ordersCollectedLast30Days: 0,
    ordersCollectedLifetime: 0,
    dailySession: {
      loginTime: "Awaiting Approval",
      logoutTime: "Inactive",
      activeMinutesToday: 0,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: false,
    },
    kyc: {
      nidNumber: "19985544332211009",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "House 28, Road 11, Banani, Dhaka",
      permanentAddress: "Kandirpar, Cumilla Sadar, Cumilla",
      district: "Dhaka",
      thana: "Gulshan",
      emergencyContactName: "Dr. Rafiqul Jahan (Father)",
      emergencyContactPhone: "01711443322",
      submittedAt: "8 Sep 2026, 02:40 PM",
    },
  },
  {
    id: "staff-6",
    name: "Mehedi Hassan",
    email: "mehedi@tatkabazar.com",
    role: "FINANCE",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    phone: "01600445566",
    address: "Block D, Bashundhara R/A, Dhaka",
    department: "Accounts & Vendor Settlements",
    assignedBranch: "Headquarters",
    joinedDate: "15 Aug 2025",
    lastLogin: "Today, 10:15 AM",
    invitedAt: "15 Aug 2025",
    invitedBy: "Tamim Khan",
    ordersCollectedToday: 9,
    ordersCollectedLast30Days: 180,
    ordersCollectedLifetime: 590,
    dailySession: {
      loginTime: "10:15 AM",
      logoutTime: "06:10 PM",
      activeMinutesToday: 475,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: false,
    },
    kyc: {
      nidNumber: "19926677889900112",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "Block D, Bashundhara R/A, Dhaka",
      permanentAddress: "Shibganj, Bogura",
      district: "Dhaka",
      thana: "Vatara",
      emergencyContactName: "Kamal Hassan (Elder Brother)",
      emergencyContactPhone: "01733221100",
      submittedAt: "16 Aug 2025",
      verifiedAt: "17 Aug 2025",
    },
  },
  {
    id: "staff-7",
    name: "Afsana Mimi",
    email: "afsana@tatkabazar.com",
    role: "SUPPORT_STAFF",
    status: "PENDING",
    kycStatus: "SUBMITTED",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    phone: "01877665544",
    address: "Holding 14, College Road, Barguna Sadar",
    department: "Coastal Hub Customer Desk",
    assignedBranch: "Barguna Coastal Hub",
    joinedDate: "8 Sep 2026",
    lastLogin: "Pending Verification",
    invitedAt: "8 Sep 2026",
    invitedBy: "Tamim Khan",
    ordersCollectedToday: 0,
    ordersCollectedLast30Days: 0,
    ordersCollectedLifetime: 0,
    dailySession: {
      loginTime: "Awaiting Approval",
      logoutTime: "Inactive",
      activeMinutesToday: 0,
      lastActiveDate: "2026-09-09",
      isCurrentlyOnline: false,
    },
    kyc: {
      nidNumber: "19990412345678901",
      nidFrontUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      nidBackUrl: "https://images.unsplash.com/photo-1589330694653-dad6bc01cf0f?w=600&auto=format&fit=crop&q=80",
      presentAddress: "College Road, Barguna Sadar, Barguna",
      permanentAddress: "College Road, Barguna Sadar, Barguna",
      district: "Barguna",
      thana: "Barguna Sadar",
      emergencyContactName: "Mokbul Hossain (Father)",
      emergencyContactPhone: "01719887766",
      submittedAt: "8 Sep 2026, 06:15 PM",
    },
  },
];

// ── Orders ───────────────────────────────────────────────────────────────────

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: "ord-bg-1711",
    orderNumber: "BG-1711",
    storeName: "Tatka Bazar",
    customerName: "Md Tamim",
    customerPhone: "01905276822",
    customerAddress: "f",
    email: "guest_01905276822@tatkabazar.com",
    deliveryArea: "Barguna",
    deliveryZone: "Barishal Division",
    deliverySlot: "Standard Delivery",
    courier: "Pathao",
    assignedModerator: "Super Admin (Default)",
    district: "Barguna",
    thana: "Bamna",
    areaNeighborhood: "Doutola",
    customerNote: "f",
    shopNote: "Internal note...",
    items: [
      { id: "item-1", name: "skin'O Deep Ocean Mineral Ro...", sku: "BG-1000", size: "100ml", price: 250, quantity: 1 },
    ],
    subtotalAmount: 250,
    deliveryCharge: 120,
    couponCode: "",
    discountAmount: 0,
    paidAmount: 0,
    memoTransactionNo: "8D3F9",
    totalAmount: 370,
    paymentMethod: "bKash",
    paymentStatus: "PAID",
    status: "PROCESSING",
    source: "STOREFRONT",
    createdAt: "2026-09-08, 12:08 AM",
    confirmedAt: "2026-09-08, 12:15 AM",
    assignedStaffId: "staff-2",
    assignedStaffName: "Rakib Hossain",
    assignedStaffAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    orderHistory: [
      { id: "h-1", timestamp: "8 Sep 2026, 12:08 AM", actorName: "Storefront Customer", actorRole: "CUSTOMER", action: "ORDER_SYNC", details: "Order placed online by Md Tamim" },
      { id: "h-2", timestamp: "8 Sep 2026, 12:10 AM", actorName: "Sync Engine", actorRole: "SYSTEM", action: "STAFF_ASSIGNED", details: "Order synced from storefront & assigned to active staff Rakib Hossain" },
    ],
    subOrders: [],
  },
  {
    id: "ord-bg-9003",
    orderNumber: "BG-9003",
    storeName: "Tatka Bazar",
    customerName: "MD ABU TYALHA",
    customerPhone: "01937086626",
    customerAddress: "zvsd",
    email: "guest_01937086626@tatkabazar.com",
    deliveryArea: "Barguna",
    deliveryZone: "Barishal Division",
    deliverySlot: "Standard Delivery",
    courier: "Steadfast",
    assignedModerator: "Super Admin (Default)",
    assignedStaffId: "staff-3",
    assignedStaffName: "Sadia Islam",
    assignedStaffAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    district: "Barguna",
    thana: "Bamna",
    areaNeighborhood: "Doutola",
    customerNote: "",
    shopNote: "",
    items: [
      { id: "item-2", name: "Organic Farm Fresh Honey", sku: "BG-2000", size: "500g", price: 250, quantity: 1 },
    ],
    subtotalAmount: 250,
    deliveryCharge: 120,
    couponCode: "",
    discountAmount: 0,
    paidAmount: 0,
    totalAmount: 370,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "CANCELLED",
    canceledBy: "ADMIN",
    canceledReason: "Order Canceled by Admin during verification (Fake address)",
    source: "STOREFRONT",
    createdAt: "2026-09-06, 05:13 PM",
    confirmedAt: "2026-09-06, 05:20 PM",
    orderHistory: [
      { id: "h-3", timestamp: "6 Sep 2026, 05:13 PM", actorName: "Storefront Customer", actorRole: "CUSTOMER", action: "ORDER_SYNC", details: "Order placed online" },
      { id: "h-4", timestamp: "6 Sep 2026, 05:15 PM", actorName: "Sync Engine", actorRole: "SYSTEM", action: "STAFF_ASSIGNED", details: "Assigned to Sadia Islam" },
      { id: "h-5", timestamp: "6 Sep 2026, 05:30 PM", actorName: "Sadia Islam", actorRole: "SUPPORT_STAFF", action: "STATUS_UPDATE", details: "Order Canceled by Admin during verification (Fake address)" },
    ],
    subOrders: [],
  },
  {
    id: "ord-1",
    orderNumber: "TB-928410",
    storeName: "Tatka Bazar",
    customerName: "Rafiq Ahmed",
    customerPhone: "01700000002",
    customerAddress: "House 27, Road 8/A, Flat 4B, Dhanmondi R/A, Dhaka",
    email: "rafiq.ahmed@gmail.com",
    deliveryArea: "Dhanmondi",
    deliveryZone: "Dhaka South",
    deliverySlot: "Morning (07:00 - 09:00 AM)",
    courier: "Tatka Express",
    assignedModerator: "Super Admin (Default)",
    district: "Dhaka",
    thana: "Dhanmondi",
    areaNeighborhood: "Road 8/A",
    customerNote: "Please deliver before 9 AM",
    shopNote: "Customer requested insulated ice drum packaging.",
    items: [
      { id: "item-3", name: "Fresh Padma Ilish (1.2kg)", sku: "TB-FISH-01", size: "1.2kg", price: 1870, quantity: 1 },
      { id: "item-4", name: "Fresh Mint Leaves", sku: "TB-VEG-04", size: "100g", price: 50, quantity: 1 },
    ],
    subtotalAmount: 1920,
    deliveryCharge: 60,
    totalAmount: 1980,
    paymentMethod: "bKash",
    paymentStatus: "PAID",
    status: "SHIPPED",
    source: "STOREFRONT",
    createdAt: "2026-09-08, 07:15 AM",
    confirmedAt: "2026-09-08, 07:28 AM",
    assignedRiderId: "rider-1",
    assignedRiderName: "Karim Molla (Motorcycle)",
    assignedVendorId: "vendor-padma-fish",
    assignedVendorName: "Padma River Fish Supply",
    subOrders: [
      { id: "sub-1", vendorId: "vendor-padma-fish", vendorName: "Padma River Fish Supply", vendorArea: "Dhanmondi", itemsCount: 2, subtotal: 1870, status: "SHIPPED", assignedAt: "8 Sep, 07:30 AM", acceptedAt: "8 Sep, 07:35 AM" },
    ],
    internalNotes: "Customer requested insulated ice drum packaging.",
  },
  {
    id: "ord-2",
    orderNumber: "TB-928411",
    customerName: "Farzana Haque",
    customerPhone: "01711223344",
    customerAddress: "House 12, Road 104, Gulshan 2, Dhaka",
    deliveryArea: "Gulshan",
    deliveryZone: "Dhaka North",
    deliverySlot: "Noon Express (12:00 - 02:00 PM)",
    totalAmount: 3450,
    paymentMethod: "SSLCOMMERZ",
    paymentStatus: "PAID",
    status: "PREPARING",
    source: "STOREFRONT",
    createdAt: "8 Sep 2026, 08:30 AM",
    confirmedAt: "8 Sep 2026, 08:40 AM",
    assignedVendorId: "tatka-official",
    assignedVendorName: "Tatka Bazar Central Stock",
    subOrders: [
      { id: "sub-3", vendorId: "tatka-official", vendorName: "Tatka Bazar Central Stock", vendorArea: "Gulshan", itemsCount: 4, subtotal: 3450, status: "PREPARING" },
    ],
  },
  {
    id: "ord-3",
    orderNumber: "TB-928412",
    customerName: "Mahmudur Rahman",
    customerPhone: "01811556677",
    customerAddress: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka",
    deliveryArea: "Uttara",
    deliveryZone: "Dhaka North",
    deliverySlot: "Evening (06:00 - 08:30 PM)",
    totalAmount: 1450,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "CONFIRMED",
    source: "STOREFRONT",
    createdAt: "8 Sep 2026, 09:10 AM",
    confirmedAt: "8 Sep 2026, 09:22 AM",
    subOrders: [],
  },
  {
    id: "ord-4",
    orderNumber: "TB-928413",
    customerName: "Tanveer Hassan",
    customerPhone: "01911889900",
    customerAddress: "Near Mirpur 10 Circle, Mirpur 10, Dhaka",
    deliveryArea: "Mirpur",
    deliveryZone: "Dhaka North",
    deliverySlot: "Morning (07:00 - 09:00 AM)",
    totalAmount: 820,
    paymentMethod: "NAGAD",
    paymentStatus: "PAID",
    status: "DELIVERED",
    source: "STOREFRONT",
    createdAt: "8 Sep 2026, 06:45 AM",
    confirmedAt: "8 Sep 2026, 06:52 AM",
    assignedRiderId: "rider-1",
    assignedRiderName: "Karim Molla (Motorcycle)",
    assignedVendorId: "vendor-green-grocer",
    assignedVendorName: "Green Grocer BD",
    subOrders: [
      { id: "sub-4", vendorId: "vendor-green-grocer", vendorName: "Green Grocer BD", vendorArea: "Mirpur", itemsCount: 1, subtotal: 820, status: "DELIVERED" },
    ],
  },
  {
    id: "ord-5",
    orderNumber: "TB-928414",
    customerName: "Rubina Akhter",
    customerPhone: "01600445566",
    customerAddress: "Road 5, Block A, Banasree, Rampura, Dhaka",
    deliveryArea: "Rampura",
    deliveryZone: "Dhaka East",
    deliverySlot: "Afternoon (03:00 - 06:00 PM)",
    totalAmount: 2200,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "PENDING",
    source: "STOREFRONT",
    createdAt: "8 Sep 2026, 11:30 AM",
    subOrders: [],
  },
  {
    id: "ord-6",
    orderNumber: "TB-928415",
    customerName: "Abir Chowdhury",
    customerPhone: "01755667788",
    customerAddress: "Mohakhali DOHS, Road 3, Dhaka",
    deliveryArea: "Mohakhali",
    deliveryZone: "Dhaka North",
    deliverySlot: "Morning (07:00 - 09:00 AM)",
    totalAmount: 4800,
    paymentMethod: "BKASH",
    paymentStatus: "PAID",
    status: "PENDING",
    source: "APP",
    createdAt: "8 Sep 2026, 11:55 AM",
    subOrders: [],
  },
  {
    id: "ord-7",
    orderNumber: "TB-928416",
    customerName: "Shirin Sultana",
    customerPhone: "01888990011",
    customerAddress: "Banani 11, Dhaka 1213",
    deliveryArea: "Banani",
    deliveryZone: "Dhaka North",
    deliverySlot: "Evening (06:00 - 08:30 PM)",
    totalAmount: 1650,
    paymentMethod: "NAGAD",
    paymentStatus: "UNPAID",
    status: "CANCELLED",
    source: "STOREFRONT",
    createdAt: "8 Sep 2026, 09:00 AM",
    subOrders: [],
  },
];

// ── Storefront Cloud Database Sync Pool (Awaiting Order Sync) ───────────────

export const STOREFRONT_SYNC_QUEUE: AdminOrder[] = [
  {
    id: "ord-sync-101",
    orderNumber: "BG-4421",
    storeName: "Tatka Bazar",
    customerName: "Kabir Hossain",
    customerPhone: "01722889900",
    customerAddress: "House 34, Road 11/A, Dhanmondi, Dhaka",
    email: "kabir.hossain@gmail.com",
    deliveryArea: "Dhanmondi",
    deliveryZone: "Dhaka South",
    deliverySlot: "Morning Express (08:00 - 10:00 AM)",
    courier: "Tatka Express",
    assignedModerator: "Super Admin (Default)",
    district: "Dhaka",
    thana: "Dhanmondi",
    areaNeighborhood: "Dhanmondi 11/A",
    customerNote: "Please call upon arrival",
    shopNote: "Storefront web checkout order",
    items: [
      { id: "item-sync-1", name: "Fresh Padma Ilish – Grade A (1kg)", sku: "FISH-ILISH-001", size: "1kg", price: 1100, quantity: 1 },
      { id: "item-sync-2", name: "Organic Red Farm Tomatoes", sku: "VEG-TOMATO-002", size: "1kg", price: 70, quantity: 1 },
    ],
    subtotalAmount: 1170,
    deliveryCharge: 80,
    totalAmount: 1250,
    paymentMethod: "bKash",
    paymentStatus: "PAID",
    status: "PROCESSING",
    source: "STOREFRONT",
    createdAt: "2026-09-09, 09:45 AM",
    subOrders: [],
  },
  {
    id: "ord-sync-102",
    orderNumber: "BG-5582",
    storeName: "Tatka Bazar",
    customerName: "Nusrat Parveen",
    customerPhone: "01844556677",
    customerAddress: "Sector 4, Road 7, Uttara, Dhaka",
    email: "nusrat.p@gmail.com",
    deliveryArea: "Uttara",
    deliveryZone: "Dhaka North",
    deliverySlot: "Afternoon (02:00 - 04:00 PM)",
    courier: "Pathao",
    assignedModerator: "Super Admin (Default)",
    district: "Dhaka",
    thana: "Uttara",
    areaNeighborhood: "Sector 4",
    customerNote: "Ring doorbell twice",
    shopNote: "Storefront mobile checkout order",
    items: [
      { id: "item-sync-3", name: "Cold-Pressed Mustard Oil (Kachi Ghani)", sku: "OIL-MUSTARD-004", size: "1 Liter", price: 320, quantity: 2 },
      { id: "item-sync-4", name: "Green Cucumber (Deshi Shosha)", sku: "VEG-CUCUMBER-005", size: "1kg", price: 50, quantity: 1 },
    ],
    subtotalAmount: 690,
    deliveryCharge: 60,
    totalAmount: 750,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "PROCESSING",
    source: "STOREFRONT",
    createdAt: "2026-09-09, 10:12 AM",
    subOrders: [],
  },
  {
    id: "ord-sync-103",
    orderNumber: "BG-7719",
    storeName: "Tatka Bazar",
    customerName: "Saimun Islam",
    customerPhone: "01911223344",
    customerAddress: "Block D, Section 10, Mirpur, Dhaka",
    email: "saimun@gmail.com",
    deliveryArea: "Mirpur",
    deliveryZone: "Dhaka North",
    deliverySlot: "Evening (06:00 - 08:00 PM)",
    courier: "Steadfast",
    assignedModerator: "Super Admin (Default)",
    district: "Dhaka",
    thana: "Mirpur",
    areaNeighborhood: "Mirpur 10",
    customerNote: "Deliver before 8 PM",
    shopNote: "Storefront web order",
    items: [
      { id: "item-sync-5", name: "Deshi Chicken (Country Breed)", sku: "MEAT-DESHI-005", size: "1 Full Bird", price: 420, quantity: 2 },
      { id: "item-sync-6", name: "Sundarbans Wild Forest Honey", sku: "HONEY-SUNDAR-006", size: "500g", price: 450, quantity: 1 },
    ],
    subtotalAmount: 1290,
    deliveryCharge: 70,
    totalAmount: 1360,
    paymentMethod: "bKash",
    paymentStatus: "PAID",
    status: "PROCESSING",
    source: "STOREFRONT",
    createdAt: "2026-09-09, 10:30 AM",
    subOrders: [],
  },
];

// ── Products ─────────────────────────────────────────────────────────────────

export const INITIAL_PRODUCTS: AdminProduct[] = [
  {
    id: "prod-ilish-premium",
    slug: "padma-ilish-hilsa-premium",
    nameBn: "Padma Hilsa – Full Fish (Premium Grade)",
    nameEn: "Padma Hilsa – Full Fish (Premium Grade)",
    descriptionEn: "Wild-caught Padma River Hilsa with highest fat content (>25%). Silver-scale premium grade, ideal for shorshe-ilish or bhapa.",
    sku: "FISH-ILISH-001",
    categorySlug: "fish-and-meat",
    categoryName: "Fish & Meat",
    subcategorySlug: "fresh-river-fish",
    vendorId: "vendor-padma-fish",
    vendorName: "Padma River Fish Supply",
    basePrice: 1650,
    comparePrice: 1900,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.5, unit: "kg", labelEn: "500g (half)", multiplier: 0.5 },
      { value: 1.0, unit: "kg", labelEn: "1 kg", multiplier: 1.0, popular: true },
      { value: 1.5, unit: "kg", labelEn: "1.5 kg (large fish)", multiplier: 1.5 },
      { value: 2.0, unit: "kg", labelEn: "2 kg (family pack)", multiplier: 2.0 },
    ],
    stock: 45,
    lowStockAlert: 10,
    images: [
      "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: false,
    isFeatured: true,
    isPublished: true,
    isDailyBazar: true,
    originEn: "Padma River, Rajshahi",
    freshnessGuaranteeEn: "Harvested at dawn, same-day delivery",
    rating: 4.9,
    reviewsCount: 88,
    nutritionInfo: { calories: "285 kcal", protein: "22.5g", carbs: "0.2g", fat: "19.4g (Omega-3)" },
    storageTipsEn: "Keep refrigerated. Consume within 2 days or freeze immediately.",
  },
  {
    id: "prod-tomato-organic",
    slug: "organic-red-tomatoes",
    nameBn: "Organic Red Farm Tomatoes (Pesticide Free)",
    nameEn: "Organic Red Farm Tomatoes (Pesticide Free)",
    descriptionEn: "Plump, vine-ripened red tomatoes picked daily from organic farms in Savar. Zero chemical ripening agents.",
    sku: "VEG-TOMATO-002",
    categorySlug: "vegetables",
    categoryName: "Fresh Vegetables",
    subcategorySlug: "daily-veg",
    vendorId: "vendor-green-grocer",
    vendorName: "Green Grocer BD",
    basePrice: 65,
    comparePrice: 80,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.5, unit: "kg", labelEn: "500g", multiplier: 0.5 },
      { value: 1.0, unit: "kg", labelEn: "1 kg", multiplier: 1.0, popular: true },
      { value: 2.0, unit: "kg", labelEn: "2 kg", multiplier: 2.0 },
      { value: 5.0, unit: "kg", labelEn: "5 kg (Family Pack)", multiplier: 4.8 },
    ],
    tieredPricing: [
      { minQty: 3, pricePerUnit: 60, discountPercent: 8, labelEn: "3kg+ at ৳60/kg" },
      { minQty: 10, pricePerUnit: 52, discountPercent: 20, labelEn: "10kg+ at ৳52/kg" },
    ],
    stock: 150,
    lowStockAlert: 20,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1546470427-e26264be0b11?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isDailyBazar: true,
    flashDiscount: 18,
    isPublished: true,
    originEn: "Savar & Narsingdi Organic Farms",
    freshnessGuaranteeEn: "Fresh morning harvest",
    rating: 4.8,
    reviewsCount: 142,
    nutritionInfo: { calories: "18 kcal", protein: "0.9g", carbs: "3.9g", fat: "0.2g" },
    storageTipsEn: "Keep at cool room temperature for best sweetness.",
  },
  {
    id: "prod-rice-kataribhog",
    slug: "dinajpur-kataribhog-aromatic-rice",
    nameBn: "Dinajpur Kataribhog Aromatic Rice",
    nameEn: "Dinajpur Kataribhog Aromatic Rice",
    descriptionEn: "Heritage-variety short-grain rice from Dinajpur with distinctive saffron-like aroma. Naturally sun-dried and stone-milled.",
    sku: "RICE-KATAR-003",
    categorySlug: "rice-and-staples",
    categoryName: "Rice, Lentils & Staples",
    subcategorySlug: "premium-rice",
    vendorId: "tatka-official",
    vendorName: "Tatka Bazar Central Stock",
    basePrice: 180,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1, unit: "kg", labelEn: "1 kg", multiplier: 1.0 },
      { value: 5, unit: "kg", labelEn: "5 kg bag", multiplier: 5.0, popular: true },
      { value: 10, unit: "kg", labelEn: "10 kg bag", multiplier: 9.5 },
      { value: 25, unit: "kg", labelEn: "25 kg sack", multiplier: 23.0 },
    ],
    stock: 280,
    lowStockAlert: 30,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isPublished: true,
    originEn: "Dinajpur District, Rangpur Division",
    rating: 4.9,
    reviewsCount: 234,
  },
  {
    id: "prod-mustard-oil",
    slug: "cold-pressed-mustard-oil",
    nameBn: "Cold-Pressed Mustard Oil (Kachi Ghani)",
    nameEn: "Cold-Pressed Mustard Oil (Kachi Ghani)",
    descriptionEn: "Traditional cold-press extracted mustard oil with intense aroma. Zero heat applied, preserving all natural antioxidants and omega-3.",
    sku: "OIL-MUSTARD-004",
    categorySlug: "oil-and-ghee",
    categoryName: "Oil, Ghee & Spices",
    subcategorySlug: "mustard-oil",
    vendorId: "vendor-organic-pantry",
    vendorName: "Organic Pantry BD",
    basePrice: 320,
    comparePrice: 380,
    baseUnit: "liter",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 0.5, unit: "L", labelEn: "500ml", multiplier: 0.5 },
      { value: 1.0, unit: "L", labelEn: "1 Liter", multiplier: 1.0, popular: true },
      { value: 2.0, unit: "L", labelEn: "2 Liter jar", multiplier: 2.0 },
      { value: 5.0, unit: "L", labelEn: "5 Liter tin", multiplier: 4.8 },
    ],
    stock: 120,
    lowStockAlert: 15,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: false,
    isPublished: true,
    originEn: "Rajshahi & Faridpur",
    rating: 4.7,
    reviewsCount: 97,
  },
  {
    id: "prod-deshi-chicken",
    slug: "deshi-chicken-country-breed",
    nameBn: "Deshi Chicken (Country Breed – Full Bird)",
    nameEn: "Deshi Chicken (Country Breed – Full Bird)",
    descriptionEn: "Free-range Bangladeshi country-breed chickens, naturally raised. Rich flavor and firmer texture than broiler.",
    sku: "MEAT-DESHI-005",
    categorySlug: "fish-and-meat",
    categoryName: "Fish & Meat",
    subcategorySlug: "desi-chicken",
    vendorId: "vendor-deshi-farm",
    vendorName: "Deshi Farm BD",
    basePrice: 450,
    comparePrice: 520,
    baseUnit: "piece",
    pricingType: "fixed",
    stock: 38,
    lowStockAlert: 8,
    images: [
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isPublished: true,
    originEn: "Mymensingh & Gazipur Free-Range Farms",
    rating: 4.8,
    reviewsCount: 73,
  },
  {
    id: "prod-honey-sundarbans",
    slug: "sundarbans-raw-forest-honey",
    nameBn: "Sundarbans Wild Forest Honey (Unfiltered)",
    nameEn: "Sundarbans Wild Forest Honey (Unfiltered)",
    descriptionEn: "Authentic Sundarbans mowal forest honey, ethically harvested by tribal collectors. Rich dark amber with 18% moisture or less.",
    sku: "HONEY-SUNDAR-006",
    categorySlug: "oil-and-ghee",
    categoryName: "Oil, Ghee & Spices",
    vendorId: "tatka-official",
    vendorName: "Tatka Bazar Central Stock",
    basePrice: 650,
    baseUnit: "g",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 250, unit: "g", labelEn: "250g jar", multiplier: 0.25 },
      { value: 500, unit: "g", labelEn: "500g jar", multiplier: 0.5, popular: true },
      { value: 1000, unit: "g", labelEn: "1 kg jar", multiplier: 1.0 },
    ],
    stock: 60,
    lowStockAlert: 10,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isPublished: true,
    originEn: "Sundarbans, Khulna Division",
    rating: 5.0,
    reviewsCount: 182,
  },
  {
    id: "prod-puri-ghee",
    slug: "desi-cow-ghee-pure",
    nameBn: "Pure Desi Cow Ghee (Gawr Ghee)",
    nameEn: "Pure Desi Cow Ghee (Gawr Ghee)",
    descriptionEn: "Slow-churned A2 desi cow ghee from grass-fed cows. Golden, aromatic, and traditionally made. No additives.",
    sku: "GHEE-DESI-007",
    categorySlug: "oil-and-ghee",
    categoryName: "Oil, Ghee & Spices",
    subcategorySlug: "pure-ghee",
    vendorId: "vendor-organic-pantry",
    vendorName: "Organic Pantry BD",
    basePrice: 880,
    baseUnit: "g",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 250, unit: "g", labelEn: "250g", multiplier: 0.25 },
      { value: 500, unit: "g", labelEn: "500g", multiplier: 0.5, popular: true },
      { value: 1000, unit: "g", labelEn: "1 kg", multiplier: 1.0 },
    ],
    stock: 85,
    lowStockAlert: 12,
    images: [
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: false,
    isPublished: false, // draft
    rating: 4.9,
    reviewsCount: 61,
  },
  {
    id: "prod-mango-himsagar",
    slug: "himsagar-mango-premium",
    nameBn: "Himsagar Mango – Premium Grade (Rajshahi)",
    nameEn: "Himsagar Mango – Premium Grade (Rajshahi)",
    descriptionEn: "The king of Bangladeshi mangoes. Thin skin, fiberless pulp with extraordinary sweetness. Rajshahi certified.",
    sku: "FRUIT-MANGO-008",
    categorySlug: "fruits",
    categoryName: "Fresh Fruits",
    subcategorySlug: "seasonal-fruits",
    vendorId: "vendor-green-grocer",
    vendorName: "Green Grocer BD",
    basePrice: 240,
    baseUnit: "kg",
    pricingType: "variableWeight",
    weightOptions: [
      { value: 1, unit: "kg", labelEn: "1 kg (~4-5 mangoes)", multiplier: 1.0 },
      { value: 3, unit: "kg", labelEn: "3 kg box", multiplier: 3.0, popular: true },
      { value: 5, unit: "kg", labelEn: "5 kg box", multiplier: 4.8 },
    ],
    stock: 8,
    lowStockAlert: 15,
    images: [
      "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=800&auto=format&fit=crop&q=80",
    ],
    isOrganic: true,
    isFeatured: true,
    isPublished: true,
    flashDiscount: 12,
    originEn: "Chapai Nawabganj, Rajshahi",
    rating: 4.9,
    reviewsCount: 312,
  },
];

// ── Categories ───────────────────────────────────────────────────────────────

export const INITIAL_CATEGORIES: AdminCategory[] = [
  {
    id: "cat-fish-meat",
    slug: "fish-and-meat",
    nameBn: "Fish & Meat",
    nameEn: "Fish & Meat",
    icon: "🐟",
    image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80",
    itemCount: 42,
    commissionRate: 8,
    isActive: true,
    subcategories: [
      { slug: "fresh-river-fish", nameBn: "River Fish", nameEn: "River Fish" },
      { slug: "sea-fish", nameBn: "Sea Fish", nameEn: "Sea Fish" },
      { slug: "desi-chicken", nameBn: "Country Chicken", nameEn: "Country Chicken" },
      { slug: "mutton-beef", nameBn: "Beef & Mutton", nameEn: "Beef & Mutton" },
    ],
  },
  {
    id: "cat-veg",
    slug: "vegetables",
    nameBn: "Fresh Vegetables",
    nameEn: "Fresh Vegetables",
    icon: "🥬",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80",
    itemCount: 58,
    commissionRate: 5,
    isActive: true,
    subcategories: [
      { slug: "leafy-greens", nameBn: "Leafy Greens", nameEn: "Leafy Greens" },
      { slug: "daily-veg", nameBn: "Daily Veggies", nameEn: "Daily Veggies" },
      { slug: "salad-items", nameBn: "Salad Items", nameEn: "Salad Items" },
    ],
  },
  {
    id: "cat-fruits",
    slug: "fruits",
    nameBn: "Fresh Fruits",
    nameEn: "Fresh Fruits",
    icon: "🥭",
    image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80",
    itemCount: 35,
    commissionRate: 7,
    isActive: true,
    subcategories: [
      { slug: "seasonal-fruits", nameBn: "Seasonal Fruits", nameEn: "Seasonal Fruits" },
      { slug: "imported-fruits", nameBn: "Imported Fruits", nameEn: "Imported Fruits" },
    ],
  },
  {
    id: "cat-rice-grains",
    slug: "rice-and-staples",
    nameBn: "Rice, Lentils & Staples",
    nameEn: "Rice, Lentils & Staples",
    icon: "🌾",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    itemCount: 64,
    commissionRate: 6,
    isActive: true,
    subcategories: [
      { slug: "premium-rice", nameBn: "Aromatic Rice", nameEn: "Aromatic Rice" },
      { slug: "lentils-dal", nameBn: "Organic Lentils", nameEn: "Organic Lentils" },
      { slug: "flour-atta", nameBn: "Atta & Flour", nameEn: "Atta & Flour" },
    ],
  },
  {
    id: "cat-oil-ghee",
    slug: "oil-and-ghee",
    nameBn: "Oil, Ghee & Spices",
    nameEn: "Oil, Ghee & Spices",
    icon: "🫒",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80",
    itemCount: 48,
    commissionRate: 9,
    isActive: true,
    subcategories: [
      { slug: "mustard-oil", nameBn: "Mustard Oil", nameEn: "Mustard Oil" },
      { slug: "pure-ghee", nameBn: "Desi Ghee", nameEn: "Desi Ghee" },
      { slug: "ground-spices", nameBn: "Ground Spices", nameEn: "Ground Spices" },
    ],
  },
  {
    id: "cat-dairy-eggs",
    slug: "dairy-and-eggs",
    nameBn: "Dairy, Curd & Eggs",
    nameEn: "Dairy, Curd & Eggs",
    icon: "🥛",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    itemCount: 29,
    commissionRate: 5,
    isActive: true,
    subcategories: [],
  },
];

// ── Vendors ──────────────────────────────────────────────────────────────────

export const INITIAL_VENDORS: AdminVendor[] = [
  {
    id: "vendor-barguna-fresh",
    nameBn: "Barguna Coastal Agro & Fish",
    nameEn: "Barguna Coastal Agro & Fish",
    slug: "barguna-coastal-agro",
    contactName: "Kamal Hossain",
    ownerName: "Kamal Hossain",
    phone: "01912-334455",
    email: "kamal@bargunaagro.com",
    tradeLicense: "BARG-2024-118",
    location: "Sadar Road, Barguna",
    area: "Doutola",
    district: "Barguna",
    thana: "Bamna",
    city: "Barguna",
    status: "APPROVED",
    commissionRate: 6,
    totalSales: 450000,
    payableBalance: 18000,
    totalProducts: 32,
    joinedDate: "15 Feb 2024",
    rating: 4.8,
    activeOrders: 4,
    parcelsToday: 14,
    pendingOrdersCount: 1,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "vendor-padma-fish",
    nameBn: "Padma River Fish Supply",
    nameEn: "Padma River Fish Supply",
    slug: "padma-fish-house",
    contactName: "Md. Hasibur Rahman",
    ownerName: "Md. Hasibur Rahman",
    phone: "01700-123456",
    email: "padmafish@vendor.com",
    tradeLicense: "DTLA-2023-77421",
    location: "Manikganj Ghat",
    area: "Dhanmondi",
    district: "Dhaka",
    thana: "Dhanmondi",
    city: "Dhaka",
    status: "APPROVED",
    commissionRate: 8,
    totalSales: 1840000,
    payableBalance: 48200,
    totalProducts: 24,
    joinedDate: "12 Jan 2023",
    rating: 4.9,
    activeOrders: 8,
    parcelsToday: 26,
    pendingOrdersCount: 3,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "vendor-green-grocer",
    nameBn: "Green Grocer BD",
    nameEn: "Green Grocer BD",
    slug: "green-grocer-bd",
    contactName: "Razia Begum",
    ownerName: "Razia Begum",
    phone: "01811-234567",
    email: "greengrocer@vendor.com",
    tradeLicense: "DTLA-2023-44102",
    location: "Savar",
    area: "Mohammadpur",
    district: "Dhaka",
    thana: "Mohammadpur",
    city: "Dhaka",
    status: "APPROVED",
    commissionRate: 5,
    totalSales: 920000,
    payableBalance: 22400,
    totalProducts: 48,
    joinedDate: "5 Mar 2023",
    rating: 4.8,
    activeOrders: 12,
    parcelsToday: 31,
    pendingOrdersCount: 5,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "tatka-official",
    nameBn: "Tatka Bazar Central Stock",
    nameEn: "Tatka Bazar Central Stock",
    slug: "tatka-official",
    contactName: "Tamim Khan",
    ownerName: "Tamim Khan",
    phone: "01700-000001",
    email: "stock@tatkabazar.com",
    tradeLicense: "TATKA-OWN",
    location: "Tejgaon Industrial",
    area: "Gulshan",
    district: "Dhaka",
    thana: "Gulshan",
    city: "Dhaka",
    status: "APPROVED",
    commissionRate: 0,
    totalSales: 6400000,
    payableBalance: 0,
    totalProducts: 120,
    joinedDate: "1 Jan 2023",
    rating: 5.0,
    activeOrders: 25,
    parcelsToday: 85,
    pendingOrdersCount: 2,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "vendor-organic-pantry",
    nameBn: "Organic Pantry BD",
    nameEn: "Organic Pantry BD",
    slug: "organic-pantry-bd",
    contactName: "Kamal Uddin",
    phone: "01911-345678",
    email: "organicpantry@vendor.com",
    tradeLicense: "DTLA-2024-12099",
    location: "Narsingdi",
    area: "Uttara",
    city: "Dhaka",
    status: "APPROVED",
    commissionRate: 9,
    totalSales: 345000,
    payableBalance: 12000,
    totalProducts: 35,
    joinedDate: "20 Jun 2024",
    rating: 4.7,
    activeOrders: 5,
  },
  {
    id: "vendor-deshi-farm",
    nameBn: "Deshi Farm BD",
    nameEn: "Deshi Farm BD",
    slug: "deshi-farm-bd",
    contactName: "Shafiqul Islam",
    phone: "01600-456789",
    email: "deshifarm@vendor.com",
    tradeLicense: "DTLA-2024-88001",
    location: "Gazipur",
    area: "Mirpur",
    city: "Dhaka",
    status: "PENDING",
    commissionRate: 8,
    totalSales: 0,
    payableBalance: 0,
    totalProducts: 0,
    joinedDate: "1 Sep 2026",
    rating: 0,
    activeOrders: 0,
  },
  {
    id: "vendor-bd-spice",
    nameBn: "BD Spice House",
    nameEn: "BD Spice House",
    slug: "bd-spice-house",
    contactName: "Latifa Khanam",
    phone: "01755-567890",
    email: "bdspice@vendor.com",
    tradeLicense: "DTLA-2024-54322",
    location: "Old Dhaka",
    area: "Sadarghat",
    city: "Dhaka",
    status: "SUSPENDED",
    commissionRate: 10,
    totalSales: 280000,
    payableBalance: 5800,
    totalProducts: 22,
    joinedDate: "14 Feb 2024",
    rating: 3.8,
    activeOrders: 0,
  },
];

// ── Riders ───────────────────────────────────────────────────────────────────

export const INITIAL_RIDERS: AdminRider[] = [
  {
    id: "rider-1",
    name: "Karim Molla",
    phone: "01700111222",
    email: "karim@rider.com",
    nid: "1234567890123",
    vehicleType: "MOTORCYCLE",
    assignedHubId: "hub-1",
    assignedHubName: "Dhanmondi Hub",
    area: "Dhanmondi",
    status: "BUSY",
    kycStatus: "APPROVED",
    activeDeliveriesCount: 2,
    totalDeliveriesCompleted: 485,
    rating: 4.9,
    balancePayable: 3400,
    totalEarned: 82000,
    joinedDate: "5 Feb 2023",
  },
  {
    id: "rider-2",
    name: "Abdul Alim",
    phone: "01811222333",
    email: "alim@rider.com",
    nid: "9876543210987",
    vehicleType: "MOTORCYCLE",
    assignedHubId: "hub-2",
    assignedHubName: "Gulshan Hub",
    area: "Gulshan",
    status: "ACTIVE",
    kycStatus: "APPROVED",
    activeDeliveriesCount: 1,
    totalDeliveriesCompleted: 312,
    rating: 4.7,
    balancePayable: 1800,
    totalEarned: 55000,
    joinedDate: "15 Apr 2023",
  },
  {
    id: "rider-3",
    name: "Mahfuz Khan",
    phone: "01911333444",
    email: "mahfuz@rider.com",
    nid: "5555666677778",
    vehicleType: "BICYCLE",
    assignedHubId: "hub-3",
    assignedHubName: "Mirpur Hub",
    area: "Mirpur",
    status: "ACTIVE",
    kycStatus: "APPROVED",
    activeDeliveriesCount: 0,
    totalDeliveriesCompleted: 128,
    rating: 4.5,
    balancePayable: 900,
    totalEarned: 22000,
    joinedDate: "10 Sep 2023",
  },
  {
    id: "rider-4",
    name: "Sohel Rana",
    phone: "01600444555",
    email: "sohel@rider.com",
    nid: "1122334455667",
    vehicleType: "MOTORCYCLE",
    assignedHubId: "hub-1",
    assignedHubName: "Dhanmondi Hub",
    area: "Mohammadpur",
    status: "OFFLINE",
    kycStatus: "APPROVED",
    activeDeliveriesCount: 0,
    totalDeliveriesCompleted: 223,
    rating: 4.6,
    balancePayable: 2100,
    totalEarned: 41000,
    joinedDate: "22 Jan 2024",
  },
  {
    id: "rider-5",
    name: "Rukon Uddin",
    phone: "01755555666",
    email: "rukon@rider.com",
    nid: "7788990011223",
    vehicleType: "VAN",
    assignedHubId: "hub-4",
    assignedHubName: "Uttara Hub",
    area: "Uttara",
    status: "PENDING",
    kycStatus: "SUBMITTED",
    activeDeliveriesCount: 0,
    totalDeliveriesCompleted: 0,
    rating: 0,
    balancePayable: 0,
    totalEarned: 0,
    joinedDate: "6 Sep 2026",
  },
];

// ── B2B Accounts ─────────────────────────────────────────────────────────────

export const INITIAL_B2B_ACCOUNTS: AdminB2BAccount[] = [
  {
    id: "b2b-1",
    companyName: "Meena Bazar Chain",
    tradeLicense: "MB-2022-10041",
    contactPerson: "Zahid Mia",
    phone: "01700-887766",
    email: "sourcing@meenabazar.com",
    categoryNeeded: "Fish & Meat, Vegetables",
    monthlyVolume: "৳1.5M – ৳2M",
    creditLimit: 200000,
    status: "APPROVED",
    appliedDate: "15 Jan 2024",
    notes: "Monthly settlement on 5th. Preferred morning delivery.",
  },
  {
    id: "b2b-2",
    companyName: "Shuchona Restaurant Group",
    tradeLicense: "SRG-2023-44401",
    contactPerson: "Farida Akter",
    phone: "01811-998877",
    email: "purchasing@shuchona.com",
    categoryNeeded: "Fish & Meat, Oil & Ghee",
    monthlyVolume: "৳600K – ৳800K",
    creditLimit: 80000,
    status: "APPROVED",
    appliedDate: "8 Mar 2025",
  },
  {
    id: "b2b-3",
    companyName: "Hotel Purbani International",
    tradeLicense: "PURBANI-2024-002",
    contactPerson: "Mahbub Islam",
    phone: "01911-776655",
    email: "kitchen@purbani.com",
    categoryNeeded: "All categories",
    monthlyVolume: "৳3M+",
    creditLimit: 500000,
    status: "PENDING",
    appliedDate: "5 Sep 2026",
    notes: "Large account - needs sales call before approval.",
  },
];

// ── Branches ─────────────────────────────────────────────────────────────────

export const INITIAL_BRANCHES: AdminBranch[] = [
  {
    id: "branch-1",
    nameBn: "Dhanmondi Hub",
    nameEn: "Dhanmondi Hub",
    area: "Dhanmondi",
    city: "Dhaka",
    address: "Road 15/A, House 7, Dhanmondi",
    phone: "09611-100001",
    deliveryFee: 49,
    eta: "30-45 min",
    isActive: true,
    managerName: "Farhan Ahmed",
    coverageZones: ["Dhanmondi", "Mohammadpur", "Kalabagan", "Lalmatia"],
  },
  {
    id: "branch-2",
    nameBn: "Gulshan Hub",
    nameEn: "Gulshan Hub",
    area: "Gulshan",
    city: "Dhaka",
    address: "Gulshan Circle 2, Shop 12",
    phone: "09611-100002",
    deliveryFee: 49,
    eta: "30-45 min",
    isActive: true,
    managerName: "Nusrat Jahan",
    coverageZones: ["Gulshan", "Banani", "Baridhara", "Mohakhali", "DOHS"],
  },
  {
    id: "branch-3",
    nameBn: "Mirpur Hub",
    nameEn: "Mirpur Hub",
    area: "Mirpur",
    city: "Dhaka",
    address: "Mirpur 10, Mosque Road",
    phone: "09611-100003",
    deliveryFee: 59,
    eta: "35-50 min",
    isActive: true,
    managerName: "Sadia Islam",
    coverageZones: ["Mirpur 1", "Mirpur 2", "Mirpur 10", "Mirpur 11", "Pallabi"],
  },
  {
    id: "branch-4",
    nameBn: "Uttara Hub",
    nameEn: "Uttara Hub",
    area: "Uttara",
    city: "Dhaka",
    address: "Uttara Sector 7, Main Road",
    phone: "09611-100004",
    deliveryFee: 69,
    eta: "40-55 min",
    isActive: false,
    managerName: "TBD",
    coverageZones: ["Uttara Sector 1-14", "Turag"],
  },
];

// ── Coupons ──────────────────────────────────────────────────────────────────

export const INITIAL_COUPONS: AdminCoupon[] = [
  {
    id: "coup-1",
    code: "TATKA50",
    type: "FLAT",
    value: 50,
    minOrderAmount: 500,
    usageLimit: 500,
    usedCount: 312,
    expiresAt: "30 Sep 2026",
    isActive: true,
  },
  {
    id: "coup-2",
    code: "FRESH15",
    type: "PERCENTAGE",
    value: 15,
    minOrderAmount: 800,
    usageLimit: 200,
    usedCount: 187,
    expiresAt: "15 Sep 2026",
    isActive: true,
  },
  {
    id: "coup-3",
    code: "WELCOME100",
    type: "FLAT",
    value: 100,
    minOrderAmount: 699,
    usageLimit: 1000,
    usedCount: 954,
    expiresAt: "31 Dec 2026",
    isActive: true,
    applicableCategories: ["fish-and-meat", "vegetables"],
  },
  {
    id: "coup-4",
    code: "EID2026",
    type: "PERCENTAGE",
    value: 20,
    minOrderAmount: 1200,
    usageLimit: 300,
    usedCount: 300,
    expiresAt: "30 Jun 2026",
    isActive: false,
  },
];

// ── Reviews ──────────────────────────────────────────────────────────────────

export const INITIAL_REVIEWS: AdminReview[] = [
  {
    id: "rev-1",
    productName: "Padma Hilsa – Premium Grade",
    productSlug: "padma-ilish-hilsa-premium",
    userName: "Kamal Hossain",
    rating: 5,
    comment: "Absolutely the best Ilish I've had outside of a riverside restaurant. The freshness is unmatched. Will definitely reorder!",
    date: "7 Sep 2026",
    status: "APPROVED",
  },
  {
    id: "rev-2",
    productName: "Organic Red Farm Tomatoes",
    productSlug: "organic-red-tomatoes",
    userName: "Ananya Das",
    rating: 4,
    comment: "Very fresh and tasty. A bit pricey but worth it for the organic quality. Packaging was excellent.",
    date: "7 Sep 2026",
    status: "APPROVED",
  },
  {
    id: "rev-3",
    productName: "Himsagar Mango – Premium",
    productSlug: "himsagar-mango-premium",
    userName: "Tanvir Ahmed",
    rating: 5,
    comment: "Superb quality mangoes. I've tried many vendors and Tatka Bazar has the best Himsagar hands down.",
    date: "8 Sep 2026",
    status: "PENDING",
  },
  {
    id: "rev-4",
    productName: "Sundarbans Wild Forest Honey",
    productSlug: "sundarbans-raw-forest-honey",
    userName: "Mariam Sultana",
    rating: 3,
    comment: "Good honey but jar arrived with a small crack. Customer service resolved it quickly though.",
    date: "6 Sep 2026",
    status: "PENDING",
  },
];

// ── Audit Logs ───────────────────────────────────────────────────────────────

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-1",
    actorName: "Tamim Khan",
    actorRole: "SUPER_ADMIN",
    action: "VENDOR_APPROVE",
    module: "Vendors",
    targetId: "vendor-deshi-farm",
    details: "Approved vendor application for Deshi Farm BD",
    timestamp: "8 Sep 2026, 11:02 AM",
    ipAddress: "103.106.12.44",
  },
  {
    id: "aud-2",
    actorName: "Rakib Hossain",
    actorRole: "MANAGER",
    action: "ORDER_STATUS_UPDATE",
    module: "Orders",
    targetId: "ord-2",
    details: "Changed order TB-928411 status: CONFIRMED → PREPARING",
    timestamp: "8 Sep 2026, 10:55 AM",
    ipAddress: "103.106.12.45",
  },
  {
    id: "aud-3",
    actorName: "Tamim Khan",
    actorRole: "SUPER_ADMIN",
    action: "STAFF_INVITE",
    module: "Staff",
    targetId: "staff-5",
    details: "Invited Nusrat Jahan as INVENTORY_STAFF",
    timestamp: "7 Sep 2026, 06:30 PM",
    ipAddress: "103.106.12.44",
  },
  {
    id: "aud-4",
    actorName: "Sadia Islam",
    actorRole: "SUPPORT_STAFF",
    action: "REVIEW_MODERATION",
    module: "Reviews",
    targetId: "rev-1",
    details: "Approved customer review for Padma Hilsa",
    timestamp: "7 Sep 2026, 04:15 PM",
  },
  {
    id: "aud-5",
    actorName: "Tamim Khan",
    actorRole: "SUPER_ADMIN",
    action: "PRODUCT_CREATE",
    module: "Products",
    targetId: "prod-honey-sundarbans",
    details: "Created product: Sundarbans Wild Forest Honey (HONEY-SUNDAR-006)",
    timestamp: "6 Sep 2026, 02:30 PM",
  },
  {
    id: "aud-6",
    actorName: "Farhan Ahmed",
    actorRole: "DELIVERY_COORDINATOR",
    action: "RIDER_ASSIGNMENT",
    module: "Orders",
    targetId: "ord-1",
    details: "Assigned order TB-928410 to Karim Molla (Motorcycle)",
    timestamp: "8 Sep 2026, 07:30 AM",
  },
];

// ── Customers ────────────────────────────────────────────────────────────────

export const INITIAL_CUSTOMERS: AdminCustomer[] = [
  {
    id: "cust-1",
    name: "Rafiq Ahmed",
    phone: "01700000002",
    email: "rafiq@gmail.com",
    totalOrders: 18,
    totalSpent: 24800,
    joinedDate: "14 Mar 2025",
    lastOrderDate: "8 Sep 2026",
    area: "Dhanmondi",
    status: "ACTIVE",
  },
  {
    id: "cust-2",
    name: "Farzana Haque",
    phone: "01711223344",
    email: "farzana@gmail.com",
    totalOrders: 31,
    totalSpent: 68400,
    joinedDate: "5 Jan 2025",
    lastOrderDate: "8 Sep 2026",
    area: "Gulshan",
    status: "ACTIVE",
  },
  {
    id: "cust-3",
    name: "Mahmudur Rahman",
    phone: "01811556677",
    email: "mahmud@yahoo.com",
    totalOrders: 7,
    totalSpent: 12300,
    joinedDate: "22 Jul 2025",
    lastOrderDate: "8 Sep 2026",
    area: "Uttara",
    status: "ACTIVE",
  },
  {
    id: "cust-4",
    name: "Rubina Akhter",
    phone: "01600445566",
    email: "rubina@outlook.com",
    totalOrders: 4,
    totalSpent: 8200,
    joinedDate: "12 Aug 2026",
    lastOrderDate: "8 Sep 2026",
    area: "Rampura",
    status: "ACTIVE",
  },
  {
    id: "cust-5",
    name: "Tanveer Hassan",
    phone: "01911889900",
    email: "tanveer@gmail.com",
    totalOrders: 25,
    totalSpent: 44600,
    joinedDate: "1 Dec 2024",
    lastOrderDate: "8 Sep 2026",
    area: "Mirpur",
    status: "ACTIVE",
  },
];
