// =============================================================================
// Tatka Bazar — Admin Mock Dataset & State Helpers
// =============================================================================

import {
  AdminUser,
  AdminOrder,
  AdminProduct,
  AdminCategory,
  AdminVendor,
  AdminB2BAccount,
  AdminRider,
  AdminBranch,
  AdminCoupon,
  AdminReview,
  AuditLogEntry,
} from "@/types";

export const INITIAL_ADMIN_USER: AdminUser = {
  id: "admin-super",
  name: "Super Admin",
  email: "admin@tatkabazar.com",
  role: "SUPER_ADMIN",
  lastLogin: "21 Aug 2026, 01:45 PM",
};

export const INITIAL_ORDERS: AdminOrder[] = [
  {
    id: "ord-1",
    orderNumber: "TB-928410",
    customerName: "Rafiq Ahmed",
    customerPhone: "01700000002",
    customerAddress: "House 27, Road 8/A, Flat 4B, Dhanmondi R/A, Dhaka",
    deliveryArea: "Dhanmondi",
    deliverySlot: "Morning (07:00 - 09:00 AM)",
    totalAmount: 1980,
    paymentMethod: "BKASH",
    paymentStatus: "PAID",
    status: "OUT_FOR_DELIVERY",
    createdAt: "21 Aug 2026, 07:15 AM",
    assignedRiderId: "rider-1",
    assignedRiderName: "Karim Molla (Bike Rider)",
    subOrders: [
      { id: "sub-1", vendorId: "vendor-padma-fish", vendorName: "Padma River Fish Supply", itemsCount: 2, subtotal: 1870, status: "OUT_FOR_DELIVERY" },
      { id: "sub-2", vendorId: "vendor-green-grocer", vendorName: "Green Grocer BD", itemsCount: 1, subtotal: 110, status: "OUT_FOR_DELIVERY" },
    ],
    internalNotes: "Customer requested insulated ice drum packaging.",
  },
  {
    id: "ord-2",
    orderNumber: "TB-928411",
    customerName: "Farzana Haque",
    customerPhone: "01711223344",
    customerAddress: "House 12, Road 104, Gulshan 2, Dhaka",
    deliveryArea: "Gulshan",
    deliverySlot: "Noon Express (12:00 - 02:00 PM)",
    totalAmount: 3450,
    paymentMethod: "SSLCOMMERZ",
    paymentStatus: "PAID",
    status: "PREPARING",
    createdAt: "21 Aug 2026, 08:30 AM",
    assignedRiderId: "rider-2",
    assignedRiderName: "Abdul Alim (E-Bike)",
    subOrders: [
      { id: "sub-3", vendorId: "tatka-official", vendorName: "Tatka Bazar Central Stock", itemsCount: 4, subtotal: 3450, status: "PREPARING" },
    ],
  },
  {
    id: "ord-3",
    orderNumber: "TB-928412",
    customerName: "Mahmudur Rahman",
    customerPhone: "01811556677",
    customerAddress: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka",
    deliveryArea: "Uttara",
    deliverySlot: "Evening (06:00 - 08:30 PM)",
    totalAmount: 1450,
    paymentMethod: "COD",
    paymentStatus: "UNPAID",
    status: "CONFIRMED",
    createdAt: "21 Aug 2026, 09:10 AM",
    subOrders: [
      { id: "sub-4", vendorId: "vendor-padma-fish", vendorName: "Padma River Fish Supply", itemsCount: 1, subtotal: 1450, status: "CONFIRMED" },
    ],
  },
  {
    id: "ord-4",
    orderNumber: "TB-928413",
    customerName: "Tanveer Hassan",
    customerPhone: "01911889900",
    customerAddress: "Near Mirpur 10 Circle, Dhaka",
    deliveryArea: "Mirpur",
    deliverySlot: "Morning (07:00 - 09:00 AM)",
    totalAmount: 820,
    paymentMethod: "NAGAD",
    paymentStatus: "PAID",
    status: "DELIVERED",
    createdAt: "21 Aug 2026, 06:45 AM",
    assignedRiderId: "rider-1",
    assignedRiderName: "Karim Molla (Bike Rider)",
    subOrders: [
      { id: "sub-5", vendorId: "vendor-green-grocer", vendorName: "Green Grocer BD", itemsCount: 3, subtotal: 820, status: "DELIVERED" },
    ],
  },
];

export const INITIAL_PRODUCTS: AdminProduct[] = [
  {
    id: "prod-1",
    slug: "padma-fresh-ilish-fish",
    nameBn: "Fresh Padma River Hilsa Fish (1kg+)",
    nameEn: "Fresh Padma River Hilsa Fish (1kg+)",
    sku: "FISH-ILISH-001",
    categorySlug: "fish-and-meat",
    categoryName: "Fish & Meat",
    vendorId: "vendor-padma-fish",
    vendorName: "Padma River Fish Supply",
    basePrice: 1450,
    comparePrice: 1650,
    baseUnit: "kg",
    pricingType: "variableWeight",
    tieredPricing: [
      { minQty: 2, pricePerUnit: 1400 },
      { minQty: 5, pricePerUnit: 1320 },
    ],
    stock: 28,
    lowStockAlert: 10,
    images: ["https://images.unsplash.com/photo-1544943910-4c1dc44a0b27?w=600&auto=format&fit=crop&q=80"],
    isOrganic: false,
    isPublished: true,
    expiryDate: "2026-08-23",
    rating: 4.9,
  },
  {
    id: "prod-2",
    slug: "organic-red-tomatoes",
    nameBn: "Organic Red Farm Tomatoes",
    nameEn: "Organic Red Farm Tomatoes",
    sku: "VEG-TOMATO-002",
    categorySlug: "vegetables",
    categoryName: "Vegetables",
    vendorId: "vendor-green-grocer",
    vendorName: "Green Grocer BD",
    basePrice: 65,
    comparePrice: 80,
    baseUnit: "kg",
    pricingType: "variableWeight",
    tieredPricing: [
      { minQty: 3, pricePerUnit: 60 },
      { minQty: 10, pricePerUnit: 52 },
    ],
    stock: 150,
    lowStockAlert: 30,
    images: ["https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80"],
    isOrganic: true,
    isPublished: true,
    expiryDate: "2026-08-25",
    rating: 4.8,
  },
  {
    id: "prod-3",
    slug: "dinajpur-kataribhog-aromatic-rice",
    nameBn: "Dinajpur Premium Kataribhog Aromatic Rice",
    nameEn: "Dinajpur Premium Kataribhog Aromatic Rice",
    sku: "GRAIN-KATARI-003",
    categorySlug: "rice-and-staples",
    categoryName: "Rice & Grains",
    vendorId: "tatka-official",
    vendorName: "Tatka Bazar Central Stock",
    basePrice: 110,
    comparePrice: 125,
    baseUnit: "kg",
    pricingType: "variableWeight",
    tieredPricing: [
      { minQty: 5, pricePerUnit: 105 },
      { minQty: 25, pricePerUnit: 98 },
    ],
    stock: 500,
    lowStockAlert: 100,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80"],
    isOrganic: false,
    isPublished: true,
    rating: 4.9,
  },
  {
    id: "prod-4",
    slug: "pure-gawa-ghee-bogura",
    nameBn: "Pure Desi Cow Ghee (Bogura)",
    nameEn: "Pure Desi Cow Ghee (Bogura)",
    sku: "DAIRY-GHEE-004",
    categorySlug: "oil-and-ghee",
    categoryName: "Oil & Ghee",
    vendorId: "vendor-bogra-dahi",
    vendorName: "Bogura Shahi Dairy",
    basePrice: 1350,
    comparePrice: 1500,
    baseUnit: "kg",
    pricingType: "variableWeight",
    stock: 6,
    lowStockAlert: 10,
    images: ["https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80"],
    isOrganic: false,
    isPublished: true,
    rating: 5.0,
  },
];

export const INITIAL_VENDORS: AdminVendor[] = [
  {
    id: "vendor-green-grocer",
    slug: "green-grocer-bd",
    nameBn: "Green Grocer BD",
    nameEn: "Green Grocer BD",
    contactName: "Rafiqul Islam",
    phone: "01711-889900",
    email: "greengrocer@tatkabazar.com",
    tradeLicense: "TRAD/SAVAR/445566",
    location: "Savar, Dhaka",
    status: "APPROVED",
    commissionRate: 10,
    totalSales: 345000,
    payableBalance: 48200,
    totalProducts: 48,
    joinedDate: "12 Jan 2024",
    rating: 4.9,
  },
  {
    id: "vendor-padma-fish",
    slug: "padma-fish-house",
    nameBn: "Padma River Fish Supply",
    nameEn: "Padma River Fish Supply",
    contactName: "Chand Miah Bepari",
    phone: "01722-112233",
    email: "padmafish@tatkabazar.com",
    tradeLicense: "TRAD/CHAND/998877",
    location: "Chandpur Ghat, Chandpur",
    status: "APPROVED",
    commissionRate: 8,
    totalSales: 620000,
    payableBalance: 76500,
    totalProducts: 32,
    joinedDate: "05 Nov 2023",
    rating: 4.8,
  },
  {
    id: "vendor-bogra-dahi",
    slug: "bogra-shahi-dairy",
    nameBn: "Bogura Shahi Dairy & Sweets",
    nameEn: "Bogura Shahi Dairy & Sweets",
    contactName: "Md. Golam Kibria",
    phone: "01733-445566",
    email: "bogradahi@tatkabazar.com",
    tradeLicense: "TRAD/BOGRA/112244",
    location: "Bogura Sadar, Bogura",
    status: "APPROVED",
    commissionRate: 12,
    totalSales: 185000,
    payableBalance: 24300,
    totalProducts: 18,
    joinedDate: "20 May 2024",
    rating: 5.0,
  },
  {
    id: "vendor-new-applicant",
    slug: "sylhet-tea-organic",
    nameBn: "Sylhet Organic Spice & Tea",
    nameEn: "Sylhet Organic Spice & Tea",
    contactName: "Ahmad Jaber",
    phone: "01744-990011",
    email: "sylhetorganic@gmail.com",
    tradeLicense: "TRAD/SYL/556677",
    location: "Sreemangal, Moulvibazar",
    status: "PENDING",
    commissionRate: 10,
    totalSales: 0,
    payableBalance: 0,
    totalProducts: 12,
    joinedDate: "21 Aug 2026",
    rating: 0,
  },
];

export const INITIAL_B2B_ACCOUNTS: AdminB2BAccount[] = [
  {
    id: "b2b-1",
    companyName: "Green Garden Restaurant Chain",
    tradeLicense: "TRAD/DNCC/123456/2024",
    contactPerson: "Tariq Zaman (Managing Director)",
    phone: "01700-998877",
    email: "procurement@greengarden.com.bd",
    categoryNeeded: "Rice & Grains",
    monthlyVolume: "1 Ton - 5 Ton",
    creditLimit: 250000,
    status: "APPROVED",
    appliedDate: "10 Aug 2026",
    notes: "Requires 2 sacks of Katari rice delivery every Friday morning.",
  },
  {
    id: "b2b-2",
    companyName: "Hotel Royal Palace Dhaka",
    tradeLicense: "TRAD/DSCC/998811/2023",
    contactPerson: "Nasir Uddin (F&B Manager)",
    phone: "01811-223344",
    email: "purchase@hotelroyal.com.bd",
    categoryNeeded: "Fish & Meat",
    monthlyVolume: "500 kg - 1000 kg",
    creditLimit: 0,
    status: "PENDING",
    appliedDate: "21 Aug 2026",
    notes: "Requires daily 10 kg bulk fresh Hilsa and Rui fish.",
  },
];

export const INITIAL_RIDERS: AdminRider[] = [
  {
    id: "rider-1",
    name: "Karim Molla",
    phone: "01701-998877",
    email: "rider@tatkabazar.com",
    nid: "19942691234567890",
    vehicleType: "MOTORCYCLE",
    assignedHubId: "branch-dhanmondi",
    assignedHubName: "Dhanmondi Express Hub",
    status: "ACTIVE",
    activeDeliveriesCount: 1,
    totalDeliveriesCompleted: 342,
    rating: 4.9,
    balancePayable: 4250,
  },
  {
    id: "rider-2",
    name: "Abdul Alim",
    phone: "01702-887766",
    email: "alim.rider@tatkabazar.com",
    nid: "19962699887766554",
    vehicleType: "BICYCLE",
    assignedHubId: "branch-gulshan",
    assignedHubName: "Gulshan 2 Flagship Hub",
    status: "ACTIVE",
    activeDeliveriesCount: 1,
    totalDeliveriesCompleted: 218,
    rating: 4.8,
    balancePayable: 2900,
  },
  {
    id: "rider-3",
    name: "Jashim Howlader",
    phone: "01703-776655",
    email: "jashim.rider@tatkabazar.com",
    nid: "19982691122334455",
    vehicleType: "MOTORCYCLE",
    assignedHubId: "branch-uttara",
    assignedHubName: "Uttara Express Hub",
    status: "PENDING",
    activeDeliveriesCount: 0,
    totalDeliveriesCompleted: 0,
    rating: 0,
    balancePayable: 0,
  },
];

export const INITIAL_BRANCHES: AdminBranch[] = [
  {
    id: "branch-dhanmondi",
    nameBn: "Dhanmondi Express Hub",
    nameEn: "Dhanmondi Express Hub",
    area: "Dhanmondi, Dhaka",
    address: "House 27, Road 8/A, Dhanmondi R/A, Dhaka 1209",
    phone: "01701-111000",
    deliveryFee: 49,
    eta: "30-45 mins",
    isActive: true,
    managerName: "Shafiqul Islam",
  },
  {
    id: "branch-gulshan",
    nameBn: "Gulshan 2 Flagship Hub",
    nameEn: "Gulshan 2 Flagship Hub",
    area: "Gulshan & Banani, Dhaka",
    address: "Plot 12, Road 104, Gulshan 2, Dhaka 1212",
    phone: "01701-222000",
    deliveryFee: 49,
    eta: "30-45 mins",
    isActive: true,
    managerName: "Mahbub Hasan",
  },
  {
    id: "branch-uttara",
    nameBn: "Uttara Express Hub",
    nameEn: "Uttara Express Hub",
    area: "Uttara (Sectors 1-18), Dhaka",
    address: "Sector 3, Jasimuddin Avenue, Uttara, Dhaka 1230",
    phone: "01701-333000",
    deliveryFee: 49,
    eta: "40-50 mins",
    isActive: true,
    managerName: "Ariful Haque",
  },
];

export const INITIAL_COUPONS: AdminCoupon[] = [
  {
    id: "coup-1",
    code: "WELCOME10",
    type: "PERCENTAGE",
    value: 10,
    minOrderAmount: 300,
    usageLimit: 1000,
    usedCount: 384,
    expiresAt: "2026-12-31",
    isActive: true,
  },
  {
    id: "coup-2",
    code: "TATKA50",
    type: "FLAT",
    value: 50,
    minOrderAmount: 500,
    usageLimit: 500,
    usedCount: 192,
    expiresAt: "2026-10-31",
    isActive: true,
  },
];

export const INITIAL_REVIEWS: AdminReview[] = [
  {
    id: "rev-1",
    productName: "Fresh Padma River Hilsa Fish (1kg+)",
    userName: "Tanvir Hasan",
    rating: 5,
    comment: "The Hilsa was extraordinarily fresh. Delivered before 8:30 AM on morning ice.",
    date: "21 Aug 2026",
    status: "APPROVED",
  },
  {
    id: "rev-2",
    productName: "Pure Desi Cow Ghee (Bogura)",
    userName: "Farzana Akter",
    rating: 5,
    comment: "Rich aroma and traditional granular texture. Packaging was very neat.",
    date: "20 Aug 2026",
    status: "APPROVED",
  },
  {
    id: "rev-3",
    productName: "Organic Red Farm Tomatoes",
    userName: "Saiful Islam",
    rating: 4,
    comment: "Tomatoes were fresh, crisp and well packaged.",
    date: "21 Aug 2026",
    status: "PENDING",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-1",
    actorName: "Super Admin",
    actorRole: "SUPER_ADMIN",
    action: "ORDER_STATUS_UPDATE",
    module: "Orders",
    targetId: "TB-928410",
    details: "Order status changed from PREPARING to OUT_FOR_DELIVERY and assigned to Karim Molla",
    timestamp: "21 Aug 2026, 07:45 AM",
  },
  {
    id: "aud-2",
    actorName: "Super Admin",
    actorRole: "SUPER_ADMIN",
    action: "PRICE_ADJUSTMENT",
    module: "Products",
    targetId: "FISH-ILISH-001",
    details: "Adjusted basePrice from ৳1400 to ৳1450 due to fresh river catch premium",
    timestamp: "21 Aug 2026, 06:10 AM",
  },
  {
    id: "aud-3",
    actorName: "Super Admin",
    actorRole: "SUPER_ADMIN",
    action: "VENDOR_APPROVAL",
    module: "Vendors",
    targetId: "vendor-padma-fish",
    details: "Approved vendor commission rate set to 8%",
    timestamp: "20 Aug 2026, 04:30 PM",
  },
];
